import { Cardano } from '@cardano-sdk/core';

export const protocolParameters: Cardano.ProtocolParameters = {
  protocolVersion: {
    major: 1,
    minor: 0,
    patch: 0,
  },
  coinsPerUtxoByte: 35_000,
  collateralPercentage: 852,
  committeeTermLimit: Cardano.EpochNo(200),
  costModels: new Map([]),
  dRepDeposit: 2000,
  dRepInactivityPeriod: Cardano.EpochNo(5000),
  dRepVotingThresholds: {
    committeeNoConfidence: { denominator: 3, numerator: 1 },
    committeeNormal: { denominator: 3, numerator: 1 },
    hardForkInitiation: { denominator: 7, numerator: 4 },
    motionNoConfidence: { denominator: 3, numerator: 1 },
    ppEconomicGroup: { denominator: 7, numerator: 6 },
    ppGovernanceGroup: { denominator: 7, numerator: 6 },
    ppNetworkGroup: { denominator: 7, numerator: 6 },
    ppTechnicalGroup: { denominator: 7, numerator: 6 },
    treasuryWithdrawal: { denominator: 7, numerator: 6 },
    updateConstitution: { denominator: 7, numerator: 6 },
  },
  desiredNumberOfPools: 900,
  governanceActionDeposit: 1000,
  governanceActionValidityPeriod: Cardano.EpochNo(1_000_000),
  maxBlockBodySize: 300,
  maxBlockHeaderSize: 500,
  maxCollateralInputs: 100,
  maxExecutionUnitsPerBlock: { memory: 4_294_967_296, steps: 4_294_967_296 },
  maxExecutionUnitsPerTransaction: {
    memory: 4_294_967_296,
    steps: 4_294_967_296,
  },
  maxTxSize: 400,
  maxValueSize: 954,
  minCommitteeSize: 100,
  minFeeCoefficient: 100,
  minFeeConstant: 200,
  minFeeRefScriptCostPerByte: '44.5',
  minPoolCost: 1000,
  monetaryExpansion: '0.3333333333333333',
  poolDeposit: 200_000_000,
  poolInfluence: '0.5',
  poolRetirementEpochBound: 800,
  poolVotingThresholds: {
    committeeNoConfidence: { denominator: 3, numerator: 1 },
    committeeNormal: { denominator: 3, numerator: 1 },
    hardForkInitiation: { denominator: 7, numerator: 6 },
    motionNoConfidence: { denominator: 3, numerator: 1 },
    securityRelevantParamVotingThreshold: { denominator: 3, numerator: 1 },
  },
  prices: { memory: 0.5, steps: 0.5 },
  stakeKeyDeposit: 2_000_000,
  treasuryExpansion: '0.25',
};
