# IMPORTANT: Please remember to add new labels to the `settings.yml`

# Browser extension
browser:
  - any: ['apps/browser-extension-wallet/**/*']
# Staking
staking:
  - any: ['packages/staking/**/*', '.github/workflows/packages-staking.yml']
# UI Toolkit
ui-toolkit:
  - any: ['packages/ui/**/*']
# E2E
e2e:
  - any: ['features/**/*', 'packages/e2e-tests/**/*']
# Docs
documentation:
  - any: ['docs/**/*', '**/*.md']
# CI
ci:
  - any: ['.github/**/*']
