# IMPORTANT: Please remember to add new labels to the `settings.yml`

# Browser extension
browser:
  - any: ['v1/apps/browser-extension-wallet/**/*']
# Staking
staking:
  - any: ['v1/packages/staking/**/*']
  - any: ['.github/workflows/packages-staking.yml']

# E2E
e2e:
  - any: ['v1/packages/e2e-tests/**/*']
# Docs
documentation:
  - any: ['docs/**/*', '**/*.md']
# CI
ci:
  - any: ['.github/**/*']
