# Path to sources
sonar.sources=apps/,packages/
sonar.exclusions=packages/e2e-tests/**/*,**/test/**/*,**/__test__/**/*
#sonar.inclusions=

# Path to tests
# sonar.tests=
#sonar.test.exclusions=
sonar.test.inclusions=apps/**/__tests__/**/*,packages/**/__tests__/**/*

# Source encoding
#sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
