export { Root } from './dialog-root.component';
export { Title } from './dialog-title.component';
export { Description } from './dialog-description.component';
export { Actions } from './dialog-actions.component';
export { Action } from './dialog-action.component';
export type { DialogRootProps } from './dialog-root.component';
export type { DialogTitleProps } from './dialog-title.component';
export type { DialogDescriptionProps } from './dialog-description.component';
export type { DialogActionsProps } from './dialog-actions.component';
export type { DialogActionProps } from './dialog-action.component';
