import { SharedWalletSchema } from '@src/shared-wallets/docs/schema/shared-wallet-type-autogenerated';
import { CoSigner } from '../creation-flow/AddCoSigners';
import { QuorumOptionValue } from '../creation-flow/Quorum';
import { paymentScriptKeyPath } from './sharedKeyToHash';
import { FileErrorMessage, FileValidationError } from './types';
import { getHash, getQuorumRulesByTag } from './utils';

type CreateWalletParams = {
  coSigners: CoSigner[];
  name: string;
  quorumRules: QuorumOptionValue;
};

export const validateJson = (
  file: File,
  sharedKey: string,
): Promise<{ data: CreateWalletParams; error?: FileValidationError }> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.addEventListener('load', async (event) => {
      try {
        const { metadata, nativeScript } = JSON.parse(event.target?.result as string) as SharedWalletSchema;

        const isFileRecognized = !!metadata && !!nativeScript;

        if (!isFileRecognized) {
          reject({ message: FileErrorMessage.UNRECOGNIZED });
        }

        const { participants, sharedWalletName } = metadata;

        const ownHash = await getHash(sharedKey, paymentScriptKeyPath);

        const cosignerData = await Promise.all(
          participants.map(async (item) => {
            const hash = await getHash(item.publicKey, paymentScriptKeyPath);
            return { ...item, hash };
          }),
        );

        const matchedCosigner = cosignerData.find((result) => result.hash === ownHash);

        if (!matchedCosigner) {
          reject({ message: FileErrorMessage.INVALID_KEYS });
        }

        const coSigners: CoSigner[] = participants.map((participant, id) => ({
          id: `${id}`,
          keys: participant.publicKey,
          name: participant.name,
        }));

        resolve({
          data: {
            coSigners,
            name: sharedWalletName,
            quorumRules: getQuorumRulesByTag(nativeScript.tag, nativeScript.tag === 'n_of_k' && nativeScript.n),
          },
        });
      } catch (error) {
        reject(error);
      }
    });

    reader.readAsText(file);
  });
