import { v1 as uuid } from 'uuid';
import { SharedWalletSchema } from '../../../shared-wallets/docs/schema/shared-wallet-type-autogenerated';
import { paymentScriptKeyPath } from '../../../shared-wallets/utils';
import { CoSigner } from '../creation-flow/AddCoSigners';
import { QuorumOptionValue } from '../creation-flow/Quorum';
import { FileErrorMessage, FileValidationError } from './types';
import { getHashFromPublicKey, getQuorumRulesByTag } from './utils';

type CreateWalletParams = {
  coSigners: CoSigner[];
  name: string;
  quorumRules: QuorumOptionValue;
};

export const validateJson = (
  file: File,
  sharedKey: string,
): Promise<{ data: CreateWalletParams; error?: FileValidationError }> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.addEventListener('load', async (event) => {
      try {
        const { metadata, nativeScript } = JSON.parse(event.target?.result as string) as SharedWalletSchema;

        const isFileRecognized = !!metadata && !!nativeScript;

        if (!isFileRecognized) {
          reject({ message: FileErrorMessage.UNRECOGNIZED });
        }

        const { coSigners, sharedWalletName } = metadata;

        const ownHash = await getHashFromPublicKey(sharedKey, paymentScriptKeyPath);

        const cosignerData = await Promise.all(
          coSigners.map(async (item) => {
            const hash = await getHashFromPublicKey(item.sharedWalletKey, paymentScriptKeyPath);
            return { ...item, hash };
          }),
        );

        const matchedCosigner = cosignerData.find((result) => result.hash === ownHash);

        if (!matchedCosigner) {
          reject({ message: FileErrorMessage.INVALID_KEY });
        }

        resolve({
          data: {
            coSigners: coSigners.map((cosigner) => ({ ...cosigner, id: uuid() })),
            name: sharedWalletName,
            quorumRules: getQuorumRulesByTag(nativeScript.tag, nativeScript.tag === 'n_of_k' && nativeScript.n),
          },
        });
      } catch (error) {
        reject(error);
      }
    });

    reader.readAsText(file);
  });
