import { Button, FileUpload, Flex, Text } from '@input-output-hk/lace-ui-toolkit';
import React, { ChangeEvent, useState } from 'react';
import { Trans, useTranslation } from 'react-i18next';
import { SharedWalletTransactionSchema } from '../../docs/schema/shared-wallet-transaction-type-autogenerated';
import { ErrorDialog, ErrorKind } from './ErrorDialog';

export class UnrecognizedFile extends Error {
  constructor() {
    super('UnrecognizedFile');
  }
}

const loadFileAsJson = <Content extends unknown>(file: File) =>
  new Promise<Content>((resolve, reject) => {
    const reader = new FileReader();
    reader.addEventListener('load', () => {
      if (reader.error) {
        reject(new UnrecognizedFile());
        return;
      }
      try {
        resolve(JSON.parse(reader.result as string));
      } catch {
        reject(new UnrecognizedFile());
      }
    });
    reader.readAsText(file);
  });

type CoSignEntryProps = {
  onCancel: () => void;
  onContinue: (txData: SharedWalletTransactionSchema) => void;
};

export const CoSignEntry = ({ onCancel, onContinue }: CoSignEntryProps) => {
  const { t } = useTranslation();
  const [errorKind, setErrorKind] = useState<ErrorKind | null>(null);
  const [loadedFileName, setLoadedFileName] = useState('');
  const [txData, setTxData] = useState<SharedWalletTransactionSchema | null>(null);

  const onFileChange = async (event: ChangeEvent<HTMLInputElement>) => {
    if (event.target.files.length === 0) return;
    setLoadedFileName(event.target.files[0].name);

    let sharedTransactionData: SharedWalletTransactionSchema;
    try {
      sharedTransactionData = await loadFileAsJson<SharedWalletTransactionSchema>(event.target.files[0]);
    } catch (error: unknown) {
      if (error instanceof UnrecognizedFile) {
        setErrorKind(ErrorKind.InvalidFile);
        return;
      }
      throw error;
    }

    // TODO: validate loaded data against schema
    if (!sharedTransactionData.transaction.cborHex || !sharedTransactionData.metadata) {
      setErrorKind(ErrorKind.InvalidFile);
    }

    setTxData(sharedTransactionData);
  };

  const handleContinue = () => {
    onContinue(txData);
  };

  const onRemove = () => {
    setLoadedFileName('');
    setTxData(null);
  };

  const onErrorCancel = () => {
    if (errorKind !== ErrorKind.InvalidFile) return;
    onCancel();
  };

  const onErrorConfirm = () => {
    switch (errorKind) {
      case ErrorKind.InvalidFile: {
        setErrorKind(null);
        setLoadedFileName(null);
        break;
      }

      case ErrorKind.InvalidActiveWallet:
      case ErrorKind.TxAlreadySigned:
      case ErrorKind.TxExpired:
      case ErrorKind.InsufficientFunds: {
        onCancel();
        break;
      }
    }
  };

  return (
    <>
      <Flex gap="$32" flexDirection="column" h="$fill">
        <Flex gap="$8" flexDirection="column">
          <Text.SubHeading>{t('sharedWallets.transaction.coSign.importJsonStep.title')}</Text.SubHeading>
          <Text.Body.Normal>{t('sharedWallets.transaction.coSign.importJsonStep.description')}</Text.Body.Normal>
        </Flex>
        <Flex h="$fill" w="$fill">
          <FileUpload
            id="upload-transaction-json"
            label={
              <Trans
                i18nKey="sharedWallets.transaction.coSign.importJsonStep.uploadBtnTitle"
                t={t}
                components={{
                  Link: <Text.Button color="highlight" />,
                }}
              />
            }
            accept="application/json"
            onChange={onFileChange}
            supportedFormats="Supported formats: JSON"
            removeButtonLabel="Remove"
            files={loadedFileName ? [loadedFileName] : undefined}
            onRemove={() => onRemove()}
          />
        </Flex>
        <Flex gap="$16" flexDirection="column" mb="$24" w="$fill">
          <Button.CallToAction label="Continue" onClick={handleContinue} disabled={!txData} w="$fill" />
          <Button.Secondary label="Cancel" onClick={onCancel} w="$fill" />
        </Flex>
      </Flex>
      {errorKind && <ErrorDialog errorKind={errorKind} onCancel={onErrorCancel} onConfirm={onErrorConfirm} />}
    </>
  );
};
