#!/bin/bash

SAFARI_EXTENSION_OUTPUT_RELATIVE_PATH=./wallet-extension-safari-build
SAFARI_BUILT_EXTENSION_DIR="$SAFARI_EXTENSION_OUTPUT_RELATIVE_PATH/extension-build"
SAFARI_DEBUG_BUILD_PATH="$SAFARI_BUILT_EXTENSION_DIR/Build/Products/Release"

cd "$SAFARI_EXTENSION_OUTPUT_RELATIVE_PATH/Lace"
open -n "$SAFARI_DEBUG_BUILD_PATH/Lace.app"
