export const colors = {
  $lace_typography_main_color: '',
  $lace_gradient: '',

  $buttons_primary_label_color: '',
  $buttons_primary_container_bgColor: '',
  $buttons_primary_container_borderColor: '',
  $buttons_primary_container_outlineColor: '',
  $buttons_primary_container_bgColor_pressed: '',
  $buttons_primary_container_bgColor_disabled: '',

  $buttons_cta_label_color: '',
  $buttons_cta_container_bgColor: '',
  $buttons_cta_container_outlineColor: '',
  $buttons_cta_container_bgColor_pressed: '',
  $buttons_cta_container_bgColor_disabled: '',

  $buttons_secondary_label_color: '',
  $buttons_secondary_label_color_pressed: '',
  $buttons_secondary_container_bgColor: '',
  $buttons_secondary_container_bgColor_hover: '',
  $buttons_secondary_container_bgColor_pressed: '',
  $buttons_secondary_container_bgColor_disabled: '',
  $buttons_secondary_container_outlineColor: '',

  $toggle_button_group_bgColor: '',
  $toggle_button_group_item_bgColor_hover: '',
  $toggle_button_group_item_bgColor: '',
  $toggle_button_group_item_bgColor_active: '',
  $toggle_button_group_item_outline_focused: '',
  $toggle_button_group_item_label_color: '',
  $toggle_button_group_item_label_color_hover: '',
  $toggle_button_group_item_label_color_active: '',
  $toggle_button_group_item_label_color_disabled: '',

  $card_elevated_backgroundColor: '',
  $card_greyed_backgroundColor: '',
  $card_outlined_backgroundColor: '',
  $card_outlined_borderColor: '',

  $control_buttons_label_color: '',
  $control_buttons_label_color_danger: '',
  $control_buttons_label_color_danger_pressed: '',
  $control_buttons_label_color_hover: '',
  $control_buttons_label_color_filled: '',
  $control_buttons_label_color_filled_hover: '',
  $control_buttons_label_color_extra_small: '',
  $control_buttons_container_bgColor: '',
  $control_buttons_container_bgColor_hover: '',
  $control_buttons_container_bgColor_filled: '',
  $control_buttons_container_bgColor_filled_hover: '',
  $control_buttons_container_bgColor_pressed: '',
  $control_buttons_container_bgColor_danger: '',
  $control_buttons_container_bgColor_danger_hover: '',
  $control_buttons_container_bgColor_extra_small: '',
  $control_buttons_container_bgColor_extra_small_active: '',
  $control_buttons_container_outlineColor: '',
  $control_buttons_borderColor: '',
  $control_buttons_borderColor_danger: '',

  $transparent: '',
  $variants_table_bgColor: '',
  $variants_table_borderColor: '',
  $divider_bgColor: '',

  $bundle_input_container_bgColor: '',
  $bundle_input_primary_label_color: '',
  $bundle_input_secondary_label_color: '',
  $bundle_input_error_label_color: '',
  $bundle_input_max_button_container_bgColor: '',
  $bundle_input_max_button_label_color: '',
  $bundle_input_max_button_label_color_hover: '',

  $bundle_input_remove_button_container_bgColor: '',
  $bundle_input_remove_button_container_bgColor_hover: '',
  $bundle_input_remove_button_outlineColor: '',
  $bundle_input_remove_button_label_color: '',
  $bundle_input_remove_button_label_color_hover: '',
  $bundle_input_remove_button_label_color_focused: '',

  $sub_navigation_container_borderColor: '',
  $sub_navigation_container_outlineColor: '',
  $sub_navigation_item_label_color: '',
  $sub_navigation_item_label_color_hover: '',
  $sub_navigation_item_label_color_pressed: '',
  $sub_navigation_item_label_color_focused: '',

  $navigation_button_container_bgColor: '',
  $navigation_button_container_bgColor_hover: '',
  $navigation_button_container_bgColor_pressed: '',
  $navigation_button_container_outlineColor: '',
  $navigation_button_label_color: '',
  $navigation_button_label_color_pressed: '',

  $profile_picture_avatar_label_color: '',
  $profile_picture_initials_label_color: '',
  $profile_picture_initials_container_bgColor: '',
  $profile_picture_image_container_borderColor: '',
  $profile_picture_image_container_borderColor_selected: '',

  $scrollbar_thumb_container_bgColor: '',
  $scrollbar_thumb_container_bgColor_hover: '',

  $toggle_switch_label_color: '',
  $toggle_switch_container_bgColor_on: '',
  $toggle_switch_container_bgColor_off: '',
  $toggle_switch_container_bgColor_disabled: '',
  $toggle_switch_container_outline: '',
  $toggle_switch_thumb_bgColor: '',

  $assets_table_container_bgColor_hover: '',
  $assets_table_label_primary_color: '',
  $assets_table_label_secondary_color: '',
  $assets_table_market_price_trend_up_label_color: '',
  $assets_table_market_price_trend_down_label_color: '',

  $dialog_container_bgColor: '',
  $dialog_title_color: '',
  $dialog_description_color: '',

  $side_drawer_container_bgColor: '',
  $side_drawer_separator_bgColor: '',
  $side_drawer_head_title_color: '',
  $side_drawer_content_title_color: '',
  $side_drawer_content_description_color: '',

  $search_box_container_bgColor: '',
  $search_box_container_bgColor_pressed: '',
  $search_box_container_borderColor_hover: '',
  $search_box_container_outlineColor: '',
  $search_box_label_color: '',
  $search_box_label_color_pressed: '',
  $search_box_clear_button_container_bgColor: '',
  $search_box_clear_button_container_bgColor_hover: '',
  $search_box_clear_button_container_bgColor_pressed: '',
  $search_box_clear_button_container_outlineColor: '',
  $search_box_clear_button_label_color: '',
  $search_box_clear_button_label_color_hover: '',
  $search_box_clear_button_label_color_pressed: '',

  $flow_card_container_bgColor: '',
  $flow_card_label_primary_color: '',
  $flow_card_label_secondary_color: '',

  $icon_button_container_bgColor: '',
  $icon_button_container_bgColor_hover: '',
  $icon_button_container_bgColor_pressed: '',
  $icon_button_container_outlineColor: '',
  $icon_button_label_color: '',
  $icon_button_label_color_pressed: '',

  $summary_expander_label_color: '',
  $summary_expander_container_borderColor: '',
  $summary_expander_trigger_container_bgColor: '',
  $summary_expander_trigger_container_bgColor_hover: '',
  $summary_expander_trigger_container_bgColor_pressed: '',
  $summary_expander_trigger_container_bgColor_focused: '',
  $summary_expander_trigger_container_outlineColor: '',
  $summary_expander_trigger_container_borderColor: '',
  $summary_expander_trigger_label_color: '',
  $summary_expander_trigger_label_color_pressed: '',

  $transaction_summary_label_color: '',
  $transaction_summary_secondary_label_color: '',

  $dapp_transaction_summary_type_label_color: '',
  $dapp_transaction_summary_label: '',

  $toast_bar_container_bgColor: '',
  $toast_bar_label_color: '',
  $toast_bar_icon_container_bgColor: '',
  $toast_bar_icon_label_color: '',

  $tooltip_container_bgColor: '',
  $tooltip_title_dot_bgColor: '',
  $tooltip_title_color: '',
  $tooltip_label_color: '',

  $message_title_color: '',
  $message_description_color: '',

  $input_container_bgColor: '',
  $input_container_hover_outline_color: '',
  $input_container_focused_outline_color: '',
  $input_value_color: '',
  $input_button_bgColor: '',
  $input_button_icon_color: '',
  $input_label_color: '',
  $input_error_message_color: '',

  $text_primary: '',
  $text_secondary: '',
  $text_on_gradient: '',

  $metadata_label_color: '',
  $metadata_secondary_label_color: '',

  $text_link_label_color: '',
  $text_link_label_color_visited: '',
  $text_link_label_color_disabled: '',

  $profile_dropdown_trigger_container_bgColor: '',
  $profile_dropdown_trigger_container_borderColor: '',
  $profile_dropdown_trigger_container_bgColor_hover: '',
  $profile_dropdown_trigger_container_bgColor_pressed: '',
  $profile_dropdown_trigger_container_outlineColor: '',
  $profile_dropdown_trigger_label_color: '',
  $profile_dropdown_trigger_label_color_pressed: '',

  $profile_dropdown_wallet_option_container_bgColor_hover: '',
  $profile_dropdown_wallet_option_container_bgColor_pressed: '',
  $profile_dropdown_wallet_option_container_outlineColor: '',
  $profile_dropdown_wallet_option_label_color: '',

  $profile_dropdown_wallet_status_container_borderColor: '',

  $profile_dropdown_account_item_container_bgColor_hover: '',
  $profile_dropdown_account_item_container_bgColor_pressed: '',
  $profile_dropdown_account_item_container_focus_outlineColor: '',
  $profile_dropdown_account_item_edit_icon_color: '',
  $profile_dropdown_account_item_delete_icon_color: '',

  $data_pink: '',
  $data_blue: '',
  $data_green: '',
  $data_yellow: '',
  $data_orange: '',

  $educational_card_root_container_bgColor: '',
  $educational_card_root_container_borderColor: '',

  $educational_card_item_container_bgColor: '',
  $educational_card_item_container_bgColor_hover: '',
  $educational_card_item_container_bgColor_pressed: '',
  $educational_card_item_container_outlineColor: '',
  $educational_card_item_label_color: '',
  $educational_card_item_title_color: '',
  $educational_card_item_icon_container_bgColor: '',
  $educational_card_item_icon_container_borderColor: '',

  $file_upload_container_bgColor: '',
  $file_upload_container_bgColor_hover: '',
  $file_upload_container_bgColor_pressed: '',
  $file_upload_container_bgColor_focused: '',
  $file_upload_container_outlineColor: '',
  $file_upload_container_borderColor: '',
  $file_upload_icon_container_bgColor: '',
  $file_upload_icon_container_borderColor: '',

  $checkbox_check_color: '',
  $checkbox_checked_backgroundColor: '',
  $checkbox_unchecked_backgroundColor: '',
  $checkbox_unchecked_borderColor: '',
  $checkbox_focus_color: '',
  $checkbox_hover_checked_backgroundColor: '',
  $checkbox_hover_unchecked_borderColor: '',
  $checkbox_hover_unchecked_backgroundColor: '',

  $radiobutton_focus_color: '',
  $radiobutton_hover_color: '',
  $radiobutton_indicator_backgroundColor: '',
  $radiobutton_indicator_check_color: '',
  $radiobutton_unchecked_borderColor: '',
  $radiobutton_unchecked_bgColor: '',
  $radiobutton_checked_bgColor: '',
  $radiobutton_icon_active: '',
  $radiobutton_icon_active_border_color: '',
  $radiobutton_icon_color: '',
  $radiobutton_icon_disabled_border_color: '',
  $radiobutton_icon_hover_color: '',
  $radiobutton_icon_hover_border_color: '',
  $radiobutton_icon_text_color: '',

  $select_border: '',
  $select_icon_color: '',
  $select_background_color: '',
  $select_hover_background_color: '',
  $select_input_value_color: '',
  $select_input_background_data_highlighted: '',
  $select_input_focus_color: '',
  $select_input_rest_border_color: '',
  $select_input_hover_border_color: '',

  $action_card_container_bgColor: '',
  $action_card_container_bgColor_hover: '',
  $action_card_container_bgColor_pressed: '',
  $action_card_container_bgColor_focused: '',
  $action_card_container_outlineColor: '',
  $action_card_container_borderColor: '',
  $action_card_icon_container_bgColor: '',
  $action_card_icon_container_borderColor: '',

  $auto_suggest_container_background_color: '',
  $auto_suggest_border_color: '',
  $auto_suggest_loader_color: '',
  $auto_suggest_check_color: '',
  $auto_suggest_address_color: '',
  $auto_suggest_initial_bgColor: '',
  $auto_suggest_initial_color: '',

  $stake_pool_header_text_color: '',
  $stake_pool_item_bg_hover: '',
  $stake_pool_item_text_color: '',
};

export type Colors = typeof colors;

export const laceGradient =
  'linear-gradient(94.22deg, #FF92E1 -18.3%, #FDC300 118.89%)';

export const colorTransparent = 'rgba(0, 0, 0, 0)';

export const lightColorScheme = {
  $primary_accent_purple: '#7F5AF0',
  $primary_hover_purple: '#7452DB',
  $primary_accent_purple_0_3: 'rgba(127, 90, 240, 0.3)',
  $primary_dark_grey: '#6F7786',
  $primary_dark_grey_plus: '#5F6676',
  $primary_black: '#3D3B39',
  $primary_grey: '#C0C0C0',
  $primary_light_grey_plus: '#EFEFEF',
  $primary_light_grey_plus_0_56: 'rgba(239, 239, 239, 0.56)',
  $primary_light_grey: '#F9F9F9',
  $primary_light_grey_0_56: 'rgba(249, 249, 249, 0.56)',
  $primary_white: '#FFFFFF',
  $secondary_hover_purple: '#D7CBF8',
  $secondary_lace_pink: '#FF92DE',
  $secondary_data_pink: '#FF5470',
  $secondary_hover_data_pink: '#E84D66',
  $secondary_data_orange: '#FF8E3C',
  $secondary_lace_yellow: '#FDC300',
  $secondary_cream: '#FCF5E3',
  $secondary_data_green: '#2CB67D',
  $secondary_data_blue: '#3489F7',
} as const;

export const darkColorScheme = {
  $primary_accent_purple: '#7F5AF0',
  $primary_hover_purple: 'rgba(116, 82, 219, 1)',
  $primary_accent_purple_0_3: 'rgba(127, 90, 240, 0.3)',
  $primary_light_grey: '#a9a9a9',
  $primary_light_grey_plus_0_56: 'rgba(239, 239, 239, 0.56)',
  $primary_light_grey_plus: '#f9f9f9',
  $primary_white: '#FFFFFF',
  $primary_grey: '#383838',
  $primary_mid_grey: '#333333',
  $primary_dark_grey: '#2F2F2F',
  $primary_dark_grey_plus: '#2E2E2E',
  $primary_light_black: '#282828',
  $primary_mid_black: '#252525',
  $primary_bg_black: '#1E1E1E',
  $primary_black: '#000000',
  $secondary_hover_purple: '#3B2F5D',
  $secondary_lace_pink: '#FF92DE',
  $secondary_data_pink: '#FF5470',
  $secondary_hover_data_pink: '#E84D66',
  $secondary_data_orange: '#FF8E3C',
  $secondary_lace_yellow: '#FDC300',
  $secondary_data_green: '#2CB67D',
  $secondary_data_blue: '#3489F7',
} as const;
