/**
 * Route name enums used by side-effects in this contract for navigation
 * intents. Duplicated from `@lace-lib/navigation/src/types/routes` to keep
 * contracts UI-agnostic (see ADR 28); a compile-time parity assertion in
 * `@lace-lib/navigation` fails the type-check if the two diverge.
 */

export enum TabRoutes {
  Portfolio = 'Portfolio',
  DApps = 'DApps',
  Settings = 'Settings',
  AccountCenter = 'Accounts',
  Support = 'Support',
  About = 'About',
  Contacts = 'Contacts',
  StakingCenter = 'StakingCenter',
  GovernanceCenter = 'GovernanceCenter',
  IdentityCenter = 'IdentityCenter',
  NotificationCenter = 'NotificationCenter',
  Swaps = 'Swaps',
}

export enum StackRoutes {
  Home = 'Home',
  AccountDetails = 'AccountDetails',
  WalletSettings = 'WalletSettings',
  AddWallet = 'AddWallet',
  OnboardingStart = 'OnboardingStart',
  OnboardingRestoreWallet = 'OnboardingRestoreWallet',
  OnboardingCreateWallet = 'OnboardingCreateWallet',
  OnboardingDesktopLogin = 'OnboardingDesktopLogin',
  OnboardingHardware = 'OnboardingHardware',
  OnboardingHardwareSetup = 'OnboardingHardwareSetup',
  DappExternalWebView = 'DappExternalWebView',
  ClaimPayload = 'ClaimPayload',
  ClaimSuccess = 'ClaimSuccess',
  ClaimError = 'ClaimError',
  IntroStart = 'IntroStart',
  IntroLace = 'IntroLace',
  IntroProof = 'IntroProof',
  IntroPrivacy = 'IntroPrivacy',
  IntroComplete = 'IntroComplete',
  NotificationDetails = 'NotificationDetails',
}

export enum SheetRoutes {
  RootStack = 'RootStack',
  AddedAccountSuccess = 'AddedAccountSuccess',
  AddedAccountFailed = 'AddedAccountFailed',
  AddAccount = 'AddAccount',
  CreateNewWallet = 'CreateNewWallet',
  AddWalletHardware = 'AddWalletHardware',
  AddWalletHardwareSetup = 'AddWalletHardwareSetup',
  SuccessCreateNewWallet = 'SuccessCreateNewWallet',
  RestoreWalletRecoveryPhrase = 'RestoreWalletRecoveryPhrase',
  RestoreWalletSelectBlockchains = 'RestoreWalletSelectBlockchains',
  RestoreWalletSuccess = 'RestoreWalletSuccess',
  RemoveAccount = 'RemoveAccount',
  RemoveAccountSuccess = 'RemoveAccountSuccess',
  RemoveWalletSuccess = 'RemoveWalletSuccess',
  CustomizeAccount = 'CustomizeAccount',
  CustomizeAccountSuccess = 'CustomizeAccountSuccess',
  AuthorizedDApps = 'AuthorizedDApps',
  Receive = 'Receive',
  Send = 'Send',
  AddAssets = 'AddAssets',
  AddressBook = 'AddressBook',
  AddContact = 'AddContact',
  QrScanner = 'QrScanner',
  ReviewTransaction = 'ReviewTransaction',
  SendResult = 'SendResult',
  AccountKey = 'AccountKey',
  RecoveryPhrase = 'RecoveryPhrase',
  RecoveryPhraseVerification = 'RecoveryPhraseVerification',
  SuccessRecoveryPhraseVerification = 'SuccessRecoveryPhraseVerification',
  EditFolder = 'EditFolder',
  CreateFolder = 'CreateFolder',
  HardwareWalletDiscoveryError = 'HardwareWalletDiscoveryError',
  HardwareWalletDiscoveryResults = 'HardwareWalletDiscoveryResults',
  Buy = 'Buy',
  ThemeSelection = 'ThemeSelection',
  Language = 'Language',
  NetworkSelection = 'NetworkSelection',
  FiatCurrencySheet = 'FiatCurrencySheet',
  AssetDetailBottomSheet = 'AssetDetailBottomSheet',
  PortfolioTokenSortControls = 'PortfolioTokenSortControls',
  ActivityDetail = 'ActivityDetail',
  DefaultOpenMode = 'DefaultOpenMode',
  StakingIssue = 'StakingIssue',
  ComingSoon = 'ComingSoon',
  Collateral = 'Collateral',
  BrowsePool = 'BrowsePool',
  BrowsePoolFilterControls = 'BrowsePoolFilterControls',
  StakePoolDetails = 'StakePoolDetails',
  StakeDelegation = 'StakeDelegation',
  NewDelegation = 'NewDelegation',
  DelegationSuccess = 'DelegationSuccess',
  DeregisterPool = 'DeregisterPool',
  DeregistrationSuccess = 'DeregistrationSuccess',
  EditWallet = 'EditWallet',
  EditWalletSuccess = 'EditWalletSuccess',
  ContactDetails = 'ContactDetails',
  SelectAccount = 'SelectAccount',
  DappDetail = 'DappDetail',
  DappFilterControls = 'DappFilterControls',
  AuthorizeDapp = 'AuthorizeDapp',
  SignData = 'SignData',
  SignTx = 'SignTx',
  MidnightSettings = 'MidnightSettings',
  EditTokenName = 'EditTokenName',
  DustDesignation = 'DustDesignation',
  ConnectionPending = 'ConnectionPending',
  ConnectionDetails = 'ConnectionDetails',
  ConnectionComplete = 'ConnectionComplete',
  KYCDetails = 'KYCDetails',
  KYCWebview = 'KYCWebview',
  SwapSelectSellToken = 'SwapSelectSellToken',
  SwapSelectBuyToken = 'SwapSelectBuyToken',
  SwapSlippage = 'SwapSlippage',
  SwapLiquiditySources = 'SwapLiquiditySources',
  SwapReview = 'SwapReview',
  SwapResult = 'SwapResult',
  LockSettings = 'LockSettings',
  // Governance center
  BrowseDRep = 'BrowseDRep',
  DRepDetails = 'DRepDetails',
  NewDRepDelegation = 'NewDRepDelegation',
  DRepDelegationSuccess = 'DRepDelegationSuccess',
}
