export type Flags =
  | 'PASSWORD_VERIFICATION'
  | 'DAPP_CONNECTOR'
  | 'TREZOR_HW'
  | 'TOKEN_PRICING'
  | 'DIFFERENT_MNEMONIC_LENGTHS'
  | 'NFT_FOLDERS'
  | 'MULTI_CURRENCY'
  | 'HIDE_MY_BALANCE'
  | 'MULTI_DELEGATION_STAKING'
  | 'ADA_HANDLE'
  | 'DATA_CHECK'
  | 'POSTHOG_ANALYTICS';
