import {
  UserAccountSolidRounded,
  AlertSquareSolidRounded,
  BrochureSolidRounded,
  CatalogueSolidRounded,
  EthereumSolidRounded,
  BubbleChatQuestionSolidRounded,
  DashboardSquare01SolidRounded,
  Delete02SolidRounded,
  Download04SolidRounded,
  SmileSolidRounded,
  File01SolidRounded,
  FolderAddSolidRounded,
  FolderEditSolidRounded,
  FolderOffSolidRounded,
  Settings01SolidRounded,
  UsbMemory02SolidRounded,
  ImageAdd02SolidRounded,
  ImageNotFound02SolidRounded,
  StarFaceSolidRounded,
  InformationSquareSolidRounded,
  LinkSquare02SolidRounded,
  LockKeySolidRounded,
  PlugSocketSolidRounded,
  Notification01SolidRounded,
  PassportValidSolidRounded,
  PlaySolidRounded,
  MinusPlus02SolidRounded,
  Wallet04SolidRounded,
  MessageQuestionSolidRounded,
  Analytics01Icon as Analytics01SolidRounded,
  CarouselHorizontalIcon as CarouselHorizontalSolidRounded,
  CircleArrowUpRightIcon as CircleArrowUpRightSolidRounded,
  Share08Icon as Share08SolidRounded,
  Share01Icon as Share01SolidRounded,
  BlockedIcon as BlockedSolidRounded,
  SquareArrowUpDownIcon as SquareArrowUpDownSolidRounded,
  PaintBucketIcon as PaintBucketSolidRounded,
  Alert02Icon as Alert02SolidRounded,
  UsbMemory01SolidRounded,
  Wallet02Icon as Wallet02SolidRounded,
  WalletAdd01Icon as WalletAdd01SolidRounded,
  WalletDone01Icon as WalletDone01SolidRounded,
  PaymentSuccess01Icon as PaymentSuccess01SolidRounded,
  Folder01SolidRounded,
  SquareLockCheck01Icon as SquareLockCheck01SolidRounded,
  DragDropHorizontalSolidRounded,
  DragDropHorizontalIcon,
  SquareIcon as SquareIconSolidRounded,
  LanguageSquareIcon as LanguageSquareSolidRounded,
  Money04Icon as Money04SolidRounded,
  Configuration02Icon as Configuration02SolidRounded,
  PasswordValidationIcon as PasswordValidationSolidRounded,
  FingerPrintIcon as FingerPrintSolidRounded,
  Moon02Icon as Moon02SolidRounded,
  Sun01Icon as Sun01SolidRounded,
  SmartPhone02Icon as SmartPhone02SolidRounded,
  DashboardSquareSettingIcon as DashboardSquareSettingSolidRounded,
  Search01Icon as Search01SolidRounded,
  Delete04SolidRounded,
  ImageCompositionOvalIcon as ImageCompositionOvalSolidRounded,
  Task01Icon as Task01SolidRounded,
  Calendar03Icon as Calendar03SolidRounded,
  Loading03Icon as Loading03SolidRounded,
  Coins01Icon as Coins01SolidRounded,
  GiftIcon as GiftSolidRounded,
  ArrowUp03Icon as ArrowUp03SolidRounded,
  ArrowDown03Icon as ArrowDown03SolidRounded,
  Recycle03Icon as Recycle03SolidRounded,
  UsbErrorIcon as UsbErrorSolidRounded,
  BluetoothIcon as BluetoothIconSolidRounded,
  AlarmClockIcon as AlarmClockSolidRounded,
  PencilEdit02Icon as PencilEdit02SolidRounded,
  Relieved01Icon as Relieved01SolidRounded,
  MoneySendFlow02Icon as MoneySendFlow02SolidRounded,
  Clock01Icon as Clock01SolidRounded,
  User02Icon as User02SolidRounded,
  Share05Icon as Share03SolidRounded,
  Sad01Icon as Sad01SolidRounded,
  ConversationIcon as ConversationSolidRounded,
  Contact01Icon as Contact01SolidRounded,
  Ticket03Icon as Ticket03SolidRounded,
  UserMinus01Icon as UserMinus01SolidRounded,
  TwitterSolidRounded,
  YoutubeSolidRounded,
  Facebook01Icon,
  Facebook02Icon,
  InstagramSolidRounded,
  MediumIcon,
  TiktokIcon as TiktokSolicIcon,
  RedditSolidRounded,
  TelegramSolidRounded,
  GithubSolidRounded,
  DiscordSolidRounded,
  PieChart06Icon as PieChart06SolidRounded,
  MoneyReceive01Icon as MoneyReceive01SolidRounded,
  ArrowExpandIcon as ArrowExpandIconSolid,
  SecurityCheckIcon as SecurityCheckIconSolid,
  ThumbsDownIcon as ThumbsDownIconSolid,
  Exchange01Icon as Exchange01Solid,
  FlowConnectionIcon as FlowConnectionSolidRounded,
} from '@hugeicons-pro/core-solid-rounded';
import {
  UserAccountIcon,
  PlusSignIcon,
  AlertSquareIcon,
  ArrowDown02Icon,
  ArrowLeft02Icon,
  ArrowUp02Icon,
  BinaryCodeIcon,
  BrochureIcon,
  Cancel01Icon,
  ArrowDown01Icon,
  ArrowUp01Icon,
  CatalogueIcon,
  BitcoinIcon,
  EthereumIcon,
  ChartIncreaseIcon,
  BubbleChatQuestionIcon,
  Download04Icon,
  Tick01Icon,
  TickDouble01Icon,
  Tick02Icon,
  ArrowRight01Icon,
  CloudDownloadIcon,
  Coins02Icon,
  Copy01Icon,
  DashboardSquare01Icon,
  Delete02Icon,
  Share04Icon,
  SmileIcon,
  File01Icon,
  FolderAddIcon,
  FolderEditIcon,
  FolderOffIcon,
  Settings01Icon,
  UsbMemory02Icon,
  ImageAdd02Icon,
  ImageNotFound02Icon,
  StarFaceIcon,
  InformationSquareIcon,
  LinkSquare02Icon,
  LockKeyIcon,
  PlugSocketIcon,
  Notification01Icon,
  PassportValidIcon,
  PlayIcon,
  MinusPlus02Icon,
  Wallet04Icon,
  WalletDone01Icon,
  QrCodeIcon,
  MessageQuestionIcon,
  ArrowDownRight01Icon,
  Analytics01StrokeRounded,
  CarouselHorizontalIcon,
  CircleArrowUpRightIcon,
  ArrowUpRight01Icon,
  Share08Icon,
  Share01Icon,
  BlockedIcon,
  ArrowRight03Icon,
  SquareArrowUpDownIcon,
  ArrowLeftRightIcon,
  ReloadIcon,
  PaintBucketIcon,
  Alert02Icon,
  UsbMemory01Icon,
  Wallet02Icon,
  WalletAdd01Icon,
  PaymentSuccessIcon,
  ArrowLeft01Icon,
  Folder01StrokeRounded,
  InformationCircleIcon,
  SquareLockCheck01Icon,
  SquareIcon,
  CellularNetworkIcon,
  LanguageSquareIcon,
  Money04Icon,
  Configuration02Icon,
  PasswordValidationIcon,
  FingerPrintIcon,
  Moon02Icon,
  Sun01Icon,
  SmartPhone02Icon,
  DashboardSquareSettingIcon,
  Search01Icon,
  ImageCompositionOvalIcon,
  ViewIcon,
  ViewOffIcon,
  Task01Icon,
  Calendar03Icon,
  Loading03Icon,
  Coins01Icon,
  GiftIcon,
  ArrowUp03Icon,
  ArrowDown03Icon,
  Recycle03Icon,
  Delete04Icon,
  Sad01Icon,
  UsbErrorIcon,
  Exchange01Icon,
  BluetoothIcon,
  AlarmClockIcon,
  PencilEdit02Icon,
  Relieved01Icon,
  MoneySendFlow02Icon,
  Clock01Icon,
  User02Icon,
  Share03Icon,
  ConversationIcon,
  Contact01Icon,
  Sorting05Icon,
  TextColorIcon,
  FilterIcon,
  Globe02Icon as GlobeIcon,
  Ticket03Icon,
  UserMinus01Icon,
  Mail01Icon,
  TwitterStrokeRounded,
  YoutubeStrokeRounded,
  InstagramStrokeRounded,
  TiktokIcon,
  InternetIcon,
  GlobeStrokeRounded,
  RedditStrokeRounded,
  TelegramStrokeRounded,
  GithubStrokeRounded,
  DiscordStrokeRounded,
  PieChart06Icon,
  MoneyReceive01Icon,
  ArrowExpandIcon as ArrowExpandIconStroke,
  SecurityCheckIcon as SecurityCheckIconStroke,
  ThumbsDownIcon as ThumbsDownIconStroke,
  Exchange01Icon as Exchange01IconStroke,
  FlowConnectionIcon as FlowConnectionIconStroke,
} from '@hugeicons-pro/core-stroke-rounded';

type IconSvgElement = readonly (readonly [
  string,
  {
    readonly [key: string]: number | string;
  },
])[];

type IconMapType = Record<
  string,
  { solid: IconSvgElement | null; stroke: IconSvgElement | null }
>;

export const iconMap = {
  Swap: { solid: Exchange01Solid, stroke: Exchange01IconStroke },
  Account: { solid: UserAccountSolidRounded, stroke: UserAccountIcon },
  Plus: { solid: null, stroke: PlusSignIcon }, // also old "Add"
  AlertSquare: { solid: AlertSquareSolidRounded, stroke: AlertSquareIcon }, // old "Alert" and "ExclamationMarkFill"
  AlertTriangle: { solid: Alert02SolidRounded, stroke: Alert02Icon }, // old "TriangleAlert"
  ArrowDown: { solid: null, stroke: ArrowDown02Icon }, // also old "Receive"
  ArrowExpand: {
    solid: ArrowExpandIconSolid,
    stroke: ArrowExpandIconStroke,
  },
  ArrowLeft: { solid: null, stroke: ArrowLeft02Icon },
  ArrowLeftRight: {
    solid: null,
    stroke: ArrowLeftRightIcon,
  }, // old "SwapHorizontal"
  ArrowUp: { solid: null, stroke: ArrowUp02Icon }, // also old "Sell"
  ArrowDownRight: { solid: null, stroke: ArrowDownRight01Icon }, // old "ReceiveTransaction"
  ArrowUpRight: { solid: null, stroke: ArrowUpRight01Icon }, // old "SendTransaction"
  ArrowRightSkip: { solid: null, stroke: ArrowRight03Icon }, // old "Skip"
  ArrowRightShare: {
    solid: Share01SolidRounded,
    stroke: Share01Icon,
  }, // old "ShareLink"
  BinaryCode: { solid: null, stroke: BinaryCodeIcon }, // also repeated as "InMemoryWallet"
  Brochure: { solid: BrochureSolidRounded, stroke: BrochureIcon },
  Cancel: { solid: null, stroke: Cancel01Icon },
  CaretDown: { solid: null, stroke: ArrowDown01Icon },
  CaretUp: { solid: null, stroke: ArrowUp01Icon },
  Catalogue: { solid: CatalogueSolidRounded, stroke: CatalogueIcon },
  Bitcoin: { solid: null, stroke: BitcoinIcon },
  Ethereum: { solid: EthereumSolidRounded, stroke: EthereumIcon },
  ChartIncrease: { solid: ChartIncreaseIcon, stroke: ChartIncreaseIcon },
  ChatBubble: {
    solid: BubbleChatQuestionSolidRounded,
    stroke: BubbleChatQuestionIcon,
  },
  Download: { solid: Download04SolidRounded, stroke: Download04Icon },
  Globe: { solid: null, stroke: GlobeIcon },
  Mail: { solid: null, stroke: Mail01Icon },
  Tick: { solid: null, stroke: Tick01Icon }, // also old "check"
  TickDouble: { solid: null, stroke: TickDouble01Icon }, // old "checked"
  Checkmark: { solid: null, stroke: Tick02Icon },
  CaretRight: { solid: null, stroke: ArrowRight01Icon }, // old "ChevronRight"
  CaretLeft: { solid: null, stroke: ArrowLeft01Icon },
  CloudDownload: { solid: null, stroke: CloudDownloadIcon },
  Coins: { solid: null, stroke: Coins02Icon },
  Copy: { solid: null, stroke: Copy01Icon }, // also repeated as "Paste"
  Dashboard: {
    solid: DashboardSquare01SolidRounded,
    stroke: DashboardSquare01Icon,
  },
  DashboardSquareSetting: {
    solid: DashboardSquareSettingSolidRounded,
    stroke: DashboardSquareSettingIcon,
  },
  Delete: { solid: Delete02SolidRounded, stroke: Delete02Icon },
  Delete04: { solid: Delete04SolidRounded, stroke: Delete04Icon },
  Share: { solid: null, stroke: Share04Icon }, // old "Export",
  ShareVertical: { solid: Share03SolidRounded, stroke: Share03Icon },
  Smile: { solid: SmileSolidRounded, stroke: SmileIcon }, // old "EyesClosedEmoji"
  File: { solid: File01SolidRounded, stroke: File01Icon },
  Filter: { solid: null, stroke: FilterIcon },
  FolderAdd: { solid: FolderAddSolidRounded, stroke: FolderAddIcon },
  FolderEdit: { solid: FolderEditSolidRounded, stroke: FolderEditIcon },
  FolderOff: { solid: FolderOffSolidRounded, stroke: FolderOffIcon },
  Folder01: { solid: Folder01SolidRounded, stroke: Folder01StrokeRounded },
  Settings: { solid: Settings01SolidRounded, stroke: Settings01Icon }, // old "Gear",
  HardwareWallet: { solid: UsbMemory02SolidRounded, stroke: UsbMemory02Icon }, // also repeated as "Usb",
  ImageAdd: { solid: ImageAdd02SolidRounded, stroke: ImageAdd02Icon },
  ImageNotFound: {
    solid: ImageNotFound02SolidRounded,
    stroke: ImageNotFound02Icon,
  },
  StarFace: { solid: StarFaceSolidRounded, stroke: StarFaceIcon }, // old "InLoveEmoji",
  Info: { solid: InformationSquareSolidRounded, stroke: InformationSquareIcon },
  InformationCircle: {
    solid: InformationCircleIcon,
    stroke: InformationCircleIcon,
  },
  Link: { solid: LinkSquare02SolidRounded, stroke: LinkSquare02Icon },
  LockKey: { solid: LockKeySolidRounded, stroke: LockKeyIcon },
  LockCheck: {
    solid: SquareLockCheck01SolidRounded,
    stroke: SquareLockCheck01Icon,
  },
  PlugSocket: { solid: PlugSocketSolidRounded, stroke: PlugSocketIcon }, // old "Network",
  Notification: {
    solid: Notification01SolidRounded,
    stroke: Notification01Icon,
  },
  PassportValid: {
    solid: PassportValidSolidRounded,
    stroke: PassportValidIcon,
  },
  Play: { solid: PlaySolidRounded, stroke: PlayIcon },
  PlusMinus: { solid: MinusPlus02SolidRounded, stroke: MinusPlus02Icon },
  UsbMemory: { solid: UsbMemory01SolidRounded, stroke: UsbMemory01Icon },
  Wallet: { solid: Wallet04SolidRounded, stroke: Wallet04Icon }, // also old "Portfolio"
  WalletCoin: {
    solid: Wallet02SolidRounded,
    stroke: Wallet02Icon,
  },
  WalletAdd: {
    solid: WalletAdd01SolidRounded,
    stroke: WalletAdd01Icon,
  },
  WalletCheck: {
    solid: WalletDone01SolidRounded,
    stroke: WalletDone01Icon,
  },
  QrCode: { solid: null, stroke: QrCodeIcon }, // also old "Scan"
  MessageQuestion: {
    solid: MessageQuestionSolidRounded,
    stroke: MessageQuestionIcon,
  }, // old "QuestionMarkFill",
  Analytics: {
    solid: Analytics01SolidRounded,
    stroke: Analytics01StrokeRounded,
  }, // old "Rewards"
  CarouselHorizontal: {
    solid: CarouselHorizontalSolidRounded,
    stroke: CarouselHorizontalIcon,
  }, // old "Select" and "SelectWhite"
  CircleArrowUpRight: {
    solid: CircleArrowUpRightSolidRounded,
    stroke: CircleArrowUpRightIcon,
  }, // old "Send"
  ShareNetwork: {
    solid: Share08SolidRounded,
    stroke: Share08Icon,
  }, // old "Share"
  Shield: {
    solid: BlockedSolidRounded,
    stroke: BlockedIcon,
  },
  SquareArrowUpDown: {
    solid: SquareArrowUpDownSolidRounded,
    stroke: SquareArrowUpDownIcon,
  }, // old "Swap"
  Reload: {
    solid: null,
    stroke: ReloadIcon,
  }, // old "Syncing"
  PaintBucket: {
    solid: PaintBucketSolidRounded,
    stroke: PaintBucketIcon,
  }, // old "Theme"
  PaymentSuccess: {
    solid: PaymentSuccess01SolidRounded,
    stroke: PaymentSuccessIcon,
  }, // old "Buy"
  DragDropHorizontal: {
    solid: DragDropHorizontalSolidRounded,
    stroke: DragDropHorizontalIcon,
  },
  Square: {
    solid: SquareIconSolidRounded,
    stroke: SquareIcon,
  },
  CellularNetwork: {
    solid: null,
    stroke: CellularNetworkIcon,
  },
  Language: {
    solid: LanguageSquareSolidRounded,
    stroke: LanguageSquareIcon,
  },
  Money: {
    solid: Money04SolidRounded,
    stroke: Money04Icon,
  },
  Configuration: {
    solid: Configuration02SolidRounded,
    stroke: Configuration02Icon,
  },
  PasswordValidation: {
    solid: PasswordValidationSolidRounded,
    stroke: PasswordValidationIcon,
  },
  FingerPrint: {
    solid: FingerPrintSolidRounded,
    stroke: FingerPrintIcon,
  },
  Moon: {
    solid: Moon02SolidRounded,
    stroke: Moon02Icon,
  },
  Sun: {
    solid: Sun01SolidRounded,
    stroke: Sun01Icon,
  },
  SmartPhone: {
    solid: SmartPhone02SolidRounded,
    stroke: SmartPhone02Icon,
  },
  Search: {
    solid: Search01SolidRounded,
    stroke: Search01Icon,
  },
  ImageCompositionOval: {
    solid: ImageCompositionOvalSolidRounded,
    stroke: ImageCompositionOvalIcon,
  },
  UsbError: {
    solid: UsbErrorSolidRounded,
    stroke: UsbErrorIcon,
  },
  BluetoothIcon: {
    solid: BluetoothIconSolidRounded,
    stroke: BluetoothIcon,
  },
  View: {
    solid: ViewIcon,
    stroke: ViewIcon,
  },
  ViewOff: {
    solid: ViewOffIcon,
    stroke: ViewOffIcon,
  },
  Paste: {
    solid: Task01SolidRounded,
    stroke: Task01Icon,
  },
  Calendar03: {
    solid: Calendar03SolidRounded,
    stroke: Calendar03Icon,
  },
  Loading03: {
    solid: Loading03SolidRounded,
    stroke: Loading03Icon,
  },
  Coins01: {
    solid: Coins01SolidRounded,
    stroke: Coins01Icon,
  },
  Gift: {
    solid: GiftSolidRounded,
    stroke: GiftIcon,
  },
  ArrowUp03: {
    solid: ArrowUp03SolidRounded,
    stroke: ArrowUp03Icon,
  },
  ArrowDown03: {
    solid: ArrowDown03SolidRounded,
    stroke: ArrowDown03Icon,
  },
  Recycle03: {
    solid: Recycle03SolidRounded,
    stroke: Recycle03Icon,
  },
  Sad: { solid: Sad01SolidRounded, stroke: Sad01Icon },
  Exchange: {
    solid: null,
    stroke: Exchange01Icon,
  },
  AlarmClock: {
    solid: AlarmClockSolidRounded,
    stroke: AlarmClockIcon,
  },
  PencilEdit: {
    solid: PencilEdit02SolidRounded,
    stroke: PencilEdit02Icon,
  },
  RelievedFace: {
    solid: Relieved01SolidRounded,
    stroke: Relieved01Icon,
  },
  MoneySendFlow: {
    solid: MoneySendFlow02SolidRounded,
    stroke: MoneySendFlow02Icon,
  },
  Clock: {
    solid: Clock01SolidRounded,
    stroke: Clock01Icon,
  },
  PieChart: {
    solid: PieChart06SolidRounded,
    stroke: PieChart06Icon,
  },
  User: {
    solid: User02SolidRounded,
    stroke: User02Icon,
  },
  Conversation: {
    solid: ConversationSolidRounded,
    stroke: ConversationIcon,
  },
  Contacts: {
    solid: Contact01SolidRounded,
    stroke: Contact01Icon,
  },
  Sorting: {
    solid: null,
    stroke: Sorting05Icon,
  },
  TextColor: {
    solid: null,
    stroke: TextColorIcon,
  },
  Ticket: {
    solid: Ticket03SolidRounded,
    stroke: Ticket03Icon,
  },
  UserMinus: {
    solid: UserMinus01SolidRounded,
    stroke: UserMinus01Icon,
  },
  Twitter: {
    solid: TwitterSolidRounded,
    stroke: TwitterStrokeRounded,
  },
  Youtube: {
    solid: YoutubeSolidRounded,
    stroke: YoutubeStrokeRounded,
  },
  Facebook: {
    solid: Facebook01Icon,
    stroke: Facebook02Icon,
  },
  Instagram: {
    solid: InstagramSolidRounded,
    stroke: InstagramStrokeRounded,
  },
  Medium: {
    solid: MediumIcon,
    stroke: MediumIcon,
  },
  Tiktok: {
    solid: TiktokSolicIcon,
    stroke: TiktokIcon,
  },
  Internet: {
    solid: InternetIcon,
    stroke: GlobeStrokeRounded,
  },
  Reddit: {
    solid: RedditSolidRounded,
    stroke: RedditStrokeRounded,
  },
  Telegram: {
    solid: TelegramSolidRounded,
    stroke: TelegramStrokeRounded,
  },
  Github: {
    solid: GithubSolidRounded,
    stroke: GithubStrokeRounded,
  },
  Discord: {
    solid: DiscordSolidRounded,
    stroke: DiscordStrokeRounded,
  },
  MoneyReceive01: {
    solid: MoneyReceive01SolidRounded,
    stroke: MoneyReceive01Icon,
  },
  SecurityCheck: {
    solid: SecurityCheckIconSolid,
    stroke: SecurityCheckIconStroke,
  },
  ThumbsDown: {
    solid: ThumbsDownIconSolid,
    stroke: ThumbsDownIconStroke,
  },
  FlowConnection: {
    solid: FlowConnectionSolidRounded,
    stroke: FlowConnectionIconStroke,
  },
} satisfies IconMapType;
