import { Buffer } from 'buffer';
import { readFileSync } from 'fs';
import { join } from 'path';

import { describe, expect, it } from 'vitest';

import {
  buildAccountRequest,
  parseAccountResponse,
} from '../src/flows/account';
import { buildCip8Request, parseCip8Response } from '../src/flows/cip8';
import { buildTxSignRequest, parseTxSignResponse } from '../src/flows/tx';
import { DerivationPath } from '../src/value-objects/derivation-path.vo';
import { RequestId } from '../src/value-objects/request-id.vo';
import { Xfp } from '../src/value-objects/xfp.vo';

import type { SigningPath } from '../src/messages/cardano-cip8-sign';
import type { SigningInput } from '../src/messages/cardano-tx-sign';

/**
 * Golden tests against CBOR evidence produced by the reference Python Cardano
 * SeedSigner companion + simulated device (see test/fixtures/README.md). The
 * fixtures are the source of truth for the wire format; these tests prove the
 * TypeScript codecs build byte-identical requests and parse responses to the
 * exact values the device emitted, so the two implementations cannot drift.
 *
 * The fixtures were generated by the Python reference, NOT by re-encoding with
 * this library, so the byte-equality assertions are meaningful.
 */

interface SigningPathFixture {
  index: number;
  path: number[];
}

interface AccountKeyFixture {
  account_index: number;
  xpub: string;
  path: number[];
}

interface AccountFixture {
  request_id: string;
  origin: string;
  account_indices: number[];
  key_purpose: number;
  request_cbor: string;
  response_cbor: string;
  decoded: {
    master_fingerprint: string;
    device_label: string;
    keys: AccountKeyFixture[];
  };
}

interface Cip8Fixture {
  request_id: string;
  origin: string;
  message_payload: string;
  message_text: string;
  signing_path: SigningPathFixture;
  address_bytes: string;
  xfp: string;
  expected_key_hash: string;
  request_cbor: string;
  response_cbor: string;
  decoded: {
    request_id: string;
    cose_sign1: string;
    cose_key: string;
  };
}

interface InputFixture {
  tx_hash: string;
  index: number;
  xfp: string;
  path: number[];
}

interface TxFixture {
  request_id: string;
  origin: string;
  network: number;
  sign_data: string;
  inputs: InputFixture[];
  change_outputs: never[];
  extra_signers: never[];
  payment_key_hash: string;
  request_cbor: string;
  response_cbor: string;
  decoded: {
    request_id: string;
    vkey_witness_set: string;
  };
}

interface Evidence {
  account: AccountFixture;
  cip8: Record<'drep' | 'payment' | 'stake', Cip8Fixture>;
  tx: TxFixture;
}

const evidence = JSON.parse(
  readFileSync(join(__dirname, 'fixtures', 'companion-evidence.json'), 'utf8'),
) as Evidence;

const fromHex = (hex: string): Uint8Array =>
  new Uint8Array(Buffer.from(hex, 'hex'));
const toHex = (bytes: Uint8Array): string => Buffer.from(bytes).toString('hex');

describe('golden: account export', () => {
  const fixture = evidence.account;

  it('builds a request byte-identical to the companion', () => {
    const built = buildAccountRequest(fixture.account_indices, {
      requestId: RequestId(fixture.request_id),
      origin: fixture.origin,
      keyPurpose: fixture.key_purpose,
    });
    expect(toHex(built.cbor)).toBe(fixture.request_cbor);
  });

  it('parses the companion response to the expected fields', () => {
    const parsed = parseAccountResponse(fromHex(fixture.response_cbor));
    expect(toHex(parsed.masterFingerprint)).toBe(
      fixture.decoded.master_fingerprint,
    );
    expect(parsed.deviceLabel).toBe(fixture.decoded.device_label);
    expect(parsed.requestId).toBe(fixture.request_id);
    expect(parsed.keys).toHaveLength(fixture.decoded.keys.length);
    parsed.keys.forEach((key, index) => {
      const expected = fixture.decoded.keys[index];
      expect(key.accountIndex).toBe(expected.account_index);
      expect(toHex(key.xpub)).toBe(expected.xpub);
      expect([...key.path]).toEqual(expected.path);
    });
  });
});

const cip8Credentials = ['payment', 'stake', 'drep'] as const;

describe.each(cip8Credentials)('golden: CIP-8 %s', credential => {
  const fixture = evidence.cip8[credential];

  const signingPath: SigningPath = {
    index: fixture.signing_path.index,
    path: DerivationPath(fixture.signing_path.path),
  };

  it('builds a request byte-identical to the companion', () => {
    const built = buildCip8Request({
      messagePayload: fromHex(fixture.message_payload),
      signingPath,
      addressBytes: fromHex(fixture.address_bytes),
      xfp: Xfp.fromHex(fixture.xfp),
      requestId: RequestId(fixture.request_id),
      origin: fixture.origin,
    });
    expect(toHex(built.cbor)).toBe(fixture.request_cbor);
  });

  it('parses the companion response and the key hashes to the signing credential', () => {
    const parsed = parseCip8Response(fromHex(fixture.response_cbor));
    expect(parsed.requestId).toBe(fixture.decoded.request_id);
    expect(toHex(parsed.coseSign1)).toBe(fixture.decoded.cose_sign1);
    expect(toHex(parsed.coseKey)).toBe(fixture.decoded.cose_key);
    expect(toHex(parsed.payload)).toBe(fixture.message_payload);
    expect(parsed.signature).toHaveLength(64);
    expect(parsed.key).toHaveLength(32);
  });
});

describe('golden: transaction signing', () => {
  const fixture = evidence.tx;

  const signingInputs: SigningInput[] = fixture.inputs.map(input => ({
    txHash: fromHex(input.tx_hash),
    index: input.index,
    xfp: Xfp.fromHex(input.xfp),
    path: DerivationPath(input.path),
  }));

  it('builds a request byte-identical to the companion', () => {
    const built = buildTxSignRequest({
      serializedTxBody: fromHex(fixture.sign_data),
      signingInputs,
      changeOutputs: [],
      extraSigners: [],
      network: fixture.network,
      requestId: RequestId(fixture.request_id),
      origin: fixture.origin,
    });
    expect(toHex(built.cbor)).toBe(fixture.request_cbor);
  });

  it('parses the companion response into a single applicable witness', () => {
    const parsed = parseTxSignResponse(fromHex(fixture.response_cbor));
    expect(parsed.requestId).toBe(fixture.decoded.request_id);
    expect(toHex(parsed.vkeyWitnessSet)).toBe(fixture.decoded.vkey_witness_set);
    expect(parsed.witnesses).toHaveLength(1);
    expect(parsed.witnesses[0].vkey).toHaveLength(64);
    expect(parsed.witnesses[0].signature).toHaveLength(128);
  });
});
