#!/bin/bash
# Generated by cc-statusline (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2025-08-19T05:45:09.773Z
# Theme: detailed | Colors: true | Features: directory, git, model, usage, session, tokens

input=$(cat)

# ---- color helpers (TTY-aware, respect NO_COLOR) ----
use_color=1
[ -t 1 ] || use_color=0
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- basic colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;36m'; fi; }    # cyan
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;32m'; fi; }    # green
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;35m'; fi; }  # magenta
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;33m'; fi; } # yellow
usage_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;35m'; fi; }  # magenta
cost_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;36m'; fi; }   # cyan
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- git (detect early for fallback mode) ----
git_branch=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
fi

# ---- basics ----
if command -v jq >/dev/null 2>&1; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
else
  # Fallback: Extract basic info without jq using grep/sed
  current_dir=$(echo "$input" | grep -o '"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*:.*"\([^"]*\)".*/\1/' | sed "s|^$HOME|~|g")
  [ -z "$current_dir" ] && current_dir=$(pwd | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | grep -o '"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*:.*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  model_version=""
  # Render minimal statusline without jq and exit
  printf '📁 %s%s%s' "$(dir_color)" "$current_dir" "$(rst)"
  if [ -n "$git_branch" ]; then
    printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
  fi
  printf '  🤖 %s%s%s' "$(model_color)" "$model_name" "$(rst)"
  printf '\n'
  exit 0
fi

# ---- session color (dynamic based on time remaining) ----
session_color() { 
  rem_pct=$(( 100 - session_pct ))
  if   (( rem_pct <= 10 )); then SCLR='1;31'
  elif (( rem_pct <= 25 )); then SCLR='1;33'
  else                          SCLR='1;32'; fi
  if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$SCLR"; fi
}

# ---- Native Claude Code data integration ----
session_txt=""; session_pct=0
cost_usd=""; lines_added=0; lines_removed=0
BILLING_MODE="${CLAUDE_BILLING_MODE:-api}"

# Extract native cost data from Claude Code
cost_usd=$(echo "$input" | jq -r '.cost.total_cost_usd // empty' 2>/dev/null)
lines_added=$(echo "$input" | jq -r '.cost.total_lines_added // 0' 2>/dev/null)
lines_removed=$(echo "$input" | jq -r '.cost.total_lines_removed // 0' 2>/dev/null)

# Session timer - parse local transcript JSONL (zero external dependencies)
transcript_path=$(echo "$input" | jq -r '.transcript_path // empty' 2>/dev/null)

if [ -n "$transcript_path" ] && [ -f "$transcript_path" ]; then
  # Get first API call timestamp from session JSONL
  first_api_call=$(grep -m1 '"usage"' "$transcript_path" 2>/dev/null | jq -r '.timestamp // empty' 2>/dev/null)

  if [ -n "$first_api_call" ]; then
    # Calculate 5-hour billing block (Anthropic windows)
    # Blocks: 00:00-05:00, 05:00-10:00, 10:00-15:00, 15:00-20:00, 20:00-01:00 UTC
    current_utc_hour=$(date -u +%H)
    block_start=$((10#$current_utc_hour / 5 * 5))
    block_end=$((block_start + 5))

    # Handle day wraparound (e.g., 20:00 UTC block ends at 01:00 UTC next day)
    if [ $block_end -ge 24 ]; then
      block_end=$((block_end - 24))
      block_end_date="tomorrow"
    else
      block_end_date="today"
    fi

    # Calculate remaining time until block reset
    now_sec=$(date +%s)
    block_end_sec=$(date -u -d "${block_end_date} ${block_end}:00 UTC" +%s 2>/dev/null)

    if [ -n "$block_end_sec" ] && [ "$block_end_sec" -gt 0 ]; then
      remaining=$((block_end_sec - now_sec))

      if [ $remaining -gt 0 ] && [ $remaining -lt 18000 ]; then
        rh=$((remaining / 3600))
        rm=$(((remaining % 3600) / 60))
        block_end_local=$(date -d "@${block_end_sec}" +"%H:%M" 2>/dev/null)
        session_txt="${rh}h ${rm}m until reset at ${block_end_local}"
        session_pct=$(((18000 - remaining) * 100 / 18000))
      fi
    fi
  fi
fi

# ---- render statusline ----
printf '📁 %s%s%s' "$(dir_color)" "$current_dir" "$(rst)"
# git display
if [ -n "$git_branch" ]; then
  printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
fi
printf '  🤖 %s%s%s' "$(model_color)" "$model_name" "$(rst)"
if [ -n "$model_version" ] && [ "$model_version" != "null" ]; then
  printf '  🏷️ %s%s%s' "$(version_color)" "$model_version" "$(rst)"
fi
# session time
if [ -n "$session_txt" ]; then
  printf '  ⌛ %s%s%s' "$(session_color)" "$session_txt" "$(rst)"
fi
# cost (only show for API billing mode)
if [ "$BILLING_MODE" = "api" ] && [ -n "$cost_usd" ] && [[ "$cost_usd" =~ ^[0-9.]+$ ]]; then
  printf '  💵 %s$%.4f%s' "$(cost_color)" "$cost_usd" "$(rst)"
fi
# lines changed
if [ -n "$lines_added" ] && [ -n "$lines_removed" ] && [[ "$lines_added" =~ ^[0-9]+$ ]] && [[ "$lines_removed" =~ ^[0-9]+$ ]]; then
  if [ "$lines_added" -gt 0 ] || [ "$lines_removed" -gt 0 ]; then
    printf '  📝 %s+%d -%d%s' "$(C '1;32')" "$lines_added" "$lines_removed" "$(rst)"
  fi
fi
# trailing newline (POSIX compliance)
printf '\n'
