export const USE_MULTI_DELEGATION_STAKING_GRID_VIEW = process.env.USE_MULTI_DELEGATION_STAKING_GRID_VIEW === 'true';
export const USE_MULTI_DELEGATION_STAKING_ACTIVITY = process.env.USE_MULTI_DELEGATION_STAKING_ACTIVITY === 'true';
export const USE_MULTI_DELEGATION_STAKING_FILTERS = process.env.USE_MULTI_DELEGATION_STAKING_FILTERS === 'true';
export const USE_ROS_STAKING_COLUMN = process.env.USE_ROS_STAKING_COLUMN === 'true';
