#!/usr/bin/env bash
# Seed the extension-shell live-provider env files from key material a
# monolith (apps/lace-extension) developer already has locally.
#
# Scans (first file listing a key wins; empty and `placeholder` values are
# treated as absent):
#   apps/lace-extension/webpack/.env   MAESTRO_PROJECT_ID_*
#                                      + the ADR 40 IOG-proxied service URLs
#                                      (BLOCKFROST_PROXY_URL, MAESTRO_URL_*,
#                                      MEMPOOLSPACE_URL_*, POSTHOG_API_URL,
#                                      NFT_CDN_URL, CoinGecko, SteelSwap,
#                                      Cardano Cube)
#   apps/lace-extension/.env           the EXPO_PUBLIC_-prefixed variants
#
# Writes (refusing to overwrite an existing file unless --force):
#   apps/lace-extension-shell/.env         host build knobs (read by scripts/build.mjs)
#   apps/lace-extension-guest/.env.local   guest expo build keys
#
# The guest file is `.env.local`, not `.env`: the guest build loads
# `.env.local` above every other .env file, so the keys win regardless of
# whether NODE_ENV is set (the tracked mode files commit `placeholder`).
# Key names are printed; values never are.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WEBPACK_ENV="$REPO_ROOT/apps/lace-extension/webpack/.env"
EXPO_ENV="$REPO_ROOT/apps/lace-extension/.env"
HOST_ENV="$REPO_ROOT/apps/lace-extension-shell/.env"
GUEST_ENV="$REPO_ROOT/apps/lace-extension-guest/.env.local"

FORCE=0
if [[ "${1:-}" == "--force" ]]; then FORCE=1; fi

# read_key <file> <name> → the key's value; empty when the file or key is
# absent or the value is the tracked-file `placeholder` sentinel.
read_key() {
  local file="$1" name="$2" value
  [[ -f "$file" ]] || return 0
  value="$(grep -E "^${name}=" "$file" | tail -1 | cut -d= -f2- || true)"
  if [[ "$value" == "placeholder" ]]; then value=""; fi
  printf '%s' "$value"
}

# lookup <plain-name> → first non-empty value across the source files.
lookup() {
  local plain="$1" value
  value="$(read_key "$WEBPACK_ENV" "$plain")"
  if [[ -z "$value" ]]; then
    value="$(read_key "$EXPO_ENV" "EXPO_PUBLIC_${plain}")"
  fi
  printf '%s' "$value"
}

# Provider keys BOTH builds bake.
KEYS=(
  MAESTRO_PROJECT_ID_MAINNET
  MAESTRO_PROJECT_ID_TESTNET
)

# The IOG-proxied service URLs no tracked file carries (ADR 40) — a monolith
# developer holds them in apps/lace-extension/webpack/.env after following
# docs/adr/40-remove-internal-service-url-defaults.md. The guest fails fast at
# startup without them (BLOCKFROST_PROXY_URL excepted: unset just leaves Cardano
# unprovisioned); SteelSwap alone has a public fallback baked in.
URLS=(
  BLOCKFROST_PROXY_URL
  MAESTRO_URL_MAINNET
  MAESTRO_URL_TESTNET
  MEMPOOLSPACE_URL_MAINNET
  MEMPOOLSPACE_URL_TESTNET
  POSTHOG_API_URL
  NFT_CDN_URL
  COINGECKO_API_BASE_URL
  STEELSWAP_API_BASE_URL
  CARDANO_CUBE_BASE_URL
)

declare -A VALUES
found=0
for key in "${KEYS[@]}" "${URLS[@]}"; do
  VALUES[$key]="$(lookup "$key")"
  if [[ -n "${VALUES[$key]}" ]]; then
    echo "found   $key"
    found=$((found + 1))
  else
    echo "missing $key"
  fi
done

if [[ "$found" -eq 0 ]]; then
  echo >&2
  echo "No keys found in $WEBPACK_ENV or $EXPO_ENV —" >&2
  echo "nothing to write. Take the service URLs from" >&2
  echo "docs/adr/40-remove-internal-service-url-defaults.md and fill the" >&2
  echo "files by hand instead: see apps/lace-extension-shell/.env.example." >&2
  exit 1
fi

# write_env <path> <label> <content>
write_env() {
  local path="$1" label="$2" content="$3"
  if [[ -e "$path" && "$FORCE" -ne 1 ]]; then
    echo "SKIP  $label already exists (re-run with --force to overwrite): $path"
    return 0
  fi
  printf '%s' "$content" > "$path"
  echo "WROTE $label: $path"
}

host_content="# Generated by scripts/setup-shell-env.sh (gitignored) — live-provider keys
# and service URLs copied from the apps/lace-extension env files. Knob
# reference: .env.example.
SHELL_PROVIDER=live
"
guest_content="# Generated by scripts/setup-shell-env.sh (gitignored) — live-provider keys
# and service URLs copied from the apps/lace-extension env files.
"
# Host: neither half carries a Blockfrost key any more (audit LW-14499 — the
# proxy injects it server-side), so the proxy base seeds BOTH files —
# EXPO_PUBLIC_BLOCKFROST_PROXY_URL for the guest, and verbatim for the host
# (same name across apps by convention — the host build knobs reuse the
# monolith's names). mempool.space is MAINNET ONLY here — the host's fee
# market never fetches for a non-mainnet network (it answers a constant), so
# MEMPOOLSPACE_URL_TESTNET stays guest-only, as do the remaining service URLs.
for key in "${KEYS[@]}" BLOCKFROST_PROXY_URL MAESTRO_URL_MAINNET \
  MAESTRO_URL_TESTNET MEMPOOLSPACE_URL_MAINNET; do
  [[ -n "${VALUES[$key]}" ]] || continue
  host_content+="${key}=${VALUES[$key]}"$'\n'
done
for key in "${KEYS[@]}" "${URLS[@]}"; do
  [[ -n "${VALUES[$key]}" ]] || continue
  guest_content+="EXPO_PUBLIC_${key}=${VALUES[$key]}"$'\n'
done

echo
write_env "$HOST_ENV" "host .env" "$host_content"
write_env "$GUEST_ENV" "guest .env.local" "$guest_content"

echo
echo "Done. Next builds pick these up automatically:"
echo "  (cd apps/lace-extension-shell && npm run build)   # host, live provider"
echo "  npx nx run lace-extension-guest:build             # guest"
