import type { DappCategory } from '../types';
import type { TranslationKey, TFunction } from '@lace-contract/i18n';

export const dappCategoryTranslationKeyById: Record<string, TranslationKey> = {
  'show all': 'v2.dapp-explorer.category.show-all',
  games: 'v2.dapp-explorer.category.games',
  defi: 'v2.dapp-explorer.category.defi',
  collectibles: 'v2.dapp-explorer.category.collectibles',
  marketplaces: 'v2.dapp-explorer.category.marketplaces',
  'high-risk': 'v2.dapp-explorer.category.high-risk',
  gambling: 'v2.dapp-explorer.category.gambling',
  exchanges: 'v2.dapp-explorer.category.exchanges',
  social: 'v2.dapp-explorer.category.social',
  other: 'v2.dapp-explorer.category.other',
  bridges: 'v2.dapp-explorer.category.bridges',
  swaps: 'v2.dapp-explorer.category.swaps',
  // CardanoCube categories
  ai: 'v2.dapp-explorer.category.ai',
  animals: 'v2.dapp-explorer.category.animals',
  'art-nfts': 'v2.dapp-explorer.category.art-nfts',
  'asset-tokenization': 'v2.dapp-explorer.category.asset-tokenization',
  audit: 'v2.dapp-explorer.category.audit',
  'blockchain-explorers': 'v2.dapp-explorer.category.blockchain-explorers',
  blog: 'v2.dapp-explorer.category.blog',
  'board game': 'v2.dapp-explorer.category.board-game',
  'builder-resources': 'v2.dapp-explorer.category.builder-resources',
  calendar: 'v2.dapp-explorer.category.calendar',
  'c-sharp': 'v2.dapp-explorer.category.c-sharp',
  'charity-causes': 'v2.dapp-explorer.category.charity-causes',
  'cloud-service': 'v2.dapp-explorer.category.cloud-service',
  club: 'v2.dapp-explorer.category.club',
  community: 'v2.dapp-explorer.category.community',
  'community-building-management':
    'v2.dapp-explorer.category.community-building-management',
  'computing-ai': 'v2.dapp-explorer.category.computing-ai',
  consultancy: 'v2.dapp-explorer.category.consultancy',
  'cross-chain-assets': 'v2.dapp-explorer.category.cross-chain-assets',
  'cross-chain-bridge': 'v2.dapp-explorer.category.cross-chain-bridge',
  dao: 'v2.dapp-explorer.category.dao-tools',
  'dao-tools': 'v2.dapp-explorer.category.dao-tools',
  data: 'v2.dapp-explorer.category.data',
  'decentralized-identity': 'v2.dapp-explorer.category.decentralized-identity',
  'defense-system': 'v2.dapp-explorer.category.defense-system',
  'developer-tools': 'v2.dapp-explorer.category.developer-tools',
  dotnet: 'v2.dapp-explorer.category.dotnet',
  'ecosystem-maps': 'v2.dapp-explorer.category.ecosystem-maps',
  education: 'v2.dapp-explorer.category.education',
  'engineers-for-hire': 'v2.dapp-explorer.category.engineers-for-hire',
  'exchanges-dex': 'v2.dapp-explorer.category.exchanges-dex',
  funding: 'v2.dapp-explorer.category.funding',
  'full-node-wallet': 'v2.dapp-explorer.category.full-node-wallet',
  'game-support': 'v2.dapp-explorer.category.game-support',
  gaming: 'v2.dapp-explorer.category.gaming',
  go: 'v2.dapp-explorer.category.go',
  governance: 'v2.dapp-explorer.category.governance',
  graphql: 'v2.dapp-explorer.category.graphql',
  'hardware-wallets': 'v2.dapp-explorer.category.hardware-wallets',
  haskell: 'v2.dapp-explorer.category.haskell',
  'health-care': 'v2.dapp-explorer.category.health-care',
  'housing-property': 'v2.dapp-explorer.category.housing-property',
  identity: 'v2.dapp-explorer.category.identity',
  'immutable-data': 'v2.dapp-explorer.category.immutable-data',
  'industry-solutions': 'v2.dapp-explorer.category.industry-solutions',
  infrastructure: 'v2.dapp-explorer.category.infrastructure',
  insurance: 'v2.dapp-explorer.category.insurance',
  'internet-of-things': 'v2.dapp-explorer.category.internet-of-things',
  investment_funds: 'v2.dapp-explorer.category.investment-funds',
  'investment-management': 'v2.dapp-explorer.category.investment-management',
  ispo: 'v2.dapp-explorer.category.ispo',
  java: 'v2.dapp-explorer.category.java',
  javascript: 'v2.dapp-explorer.category.javascript',
  'job-platform': 'v2.dapp-explorer.category.job-platform',
  launchpad: 'v2.dapp-explorer.category.launchpad',
  'layer-2-solution': 'v2.dapp-explorer.category.layer-2-solution',
  'lending-borrowing': 'v2.dapp-explorer.category.lending-borrowing',
  'light-wallets': 'v2.dapp-explorer.category.light-wallets',
  media: 'v2.dapp-explorer.category.media',
  'meetups-events': 'v2.dapp-explorer.category.meetups-events',
  'meme-coins': 'v2.dapp-explorer.category.meme-coins',
  metaverse: 'v2.dapp-explorer.category.metaverse',
  mmorpg: 'v2.dapp-explorer.category.mmorpg',
  music: 'v2.dapp-explorer.category.music',
  nft: 'v2.dapp-explorer.category.nft',
  'nft-marketplaces': 'v2.dapp-explorer.category.nft-marketplaces',
  nfttools: 'v2.dapp-explorer.category.nfttools',
  'partner-chain': 'v2.dapp-explorer.category.partner-chain',
  payment: 'v2.dapp-explorer.category.payment',
  'payment-solution': 'v2.dapp-explorer.category.payment-solution',
  'peer-to-peer': 'v2.dapp-explorer.category.peer-to-peer',
  'pfp-avatar-nfts': 'v2.dapp-explorer.category.pfp-avatar-nfts',
  plutus: 'v2.dapp-explorer.category.plutus',
  podcast: 'v2.dapp-explorer.category.podcast',
  popular: 'v2.dapp-explorer.category.popular',
  'prediction-market': 'v2.dapp-explorer.category.prediction-market',
  'private-transactions': 'v2.dapp-explorer.category.private-transactions',
  python: 'v2.dapp-explorer.category.python',
  racing: 'v2.dapp-explorer.category.racing',
  retail: 'v2.dapp-explorer.category.retail',
  retro: 'v2.dapp-explorer.category.retro',
  rpg: 'v2.dapp-explorer.category.rpg',
  rust: 'v2.dapp-explorer.category.rust',
  'scrolling-2d': 'v2.dapp-explorer.category.scrolling-2d',
  shitcoin: 'v2.dapp-explorer.category.shitcoin',
  'social-bots-tools': 'v2.dapp-explorer.category.social-bots-tools',
  stablecoin: 'v2.dapp-explorer.category.stablecoin',
  'staking-tools': 'v2.dapp-explorer.category.staking-tools',
  'store-of-value': 'v2.dapp-explorer.category.store-of-value',
  strategy: 'v2.dapp-explorer.category.strategy',
  'supply-chain': 'v2.dapp-explorer.category.supply-chain',
  telecom: 'v2.dapp-explorer.category.telecom',
  'token-distribution-tooling':
    'v2.dapp-explorer.category.token-distribution-tooling',
  tools: 'v2.dapp-explorer.category.tools',
  'trading-cards': 'v2.dapp-explorer.category.trading-cards',
  travel: 'v2.dapp-explorer.category.travel',
  'twitter-space': 'v2.dapp-explorer.category.twitter-space',
  utility: 'v2.dapp-explorer.category.utility',
  'utility-nfts': 'v2.dapp-explorer.category.utility-nfts',
  wallets: 'v2.dapp-explorer.category.wallets',
  youtube: 'v2.dapp-explorer.category.youtube',
};

export const getDappCategoryLabel = (
  t: TFunction,
  category: DappCategory,
): string => {
  const key = dappCategoryTranslationKeyById[String(category)];
  return key ? t(key) : String(category);
};
