/* eslint-disable unicorn/no-abusive-eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NativeScript = ScriptPubkey | ScriptAll | ScriptAny | ScriptNOfK | TimelockStart | TimelockExpiry;
export type Ed25519KeyHash = string;
/**
 * 32-bit unsigned integer
 */
export type UInt32 = number;
/**
 * 64-bit unsigned integer
 */
export type UInt64 = string;

/**
 * Shared wallet structure based on CIP-1854
 */
export interface SharedWalletSchema {
  metadata: {
    [k: string]: unknown;
    /**
     * The list of participants in the shared wallet
     */
    participants: {
      [k: string]: unknown;
      /**
       * The name of the participant
       */
      name: string;
      /**
       * The Ed25519KeyHash of the participant
       */
      publicKey: string;
    }[];
    /**
     * The name of the shared wallet
     */
    sharedWalletName?: string;
  };
  nativeScript: NativeScript;
}
export interface ScriptPubkey {
  pubkey: Ed25519KeyHash;
  tag: 'pubkey';
}
export interface ScriptAll {
  scripts: NativeScript[];
  tag: 'all';
}
export interface ScriptAny {
  scripts: NativeScript[];
  tag: 'any';
}
export interface ScriptNOfK {
  n: UInt32;
  scripts: NativeScript[];
  tag: 'n_of_k';
}
export interface TimelockStart {
  slot: UInt64;
  tag: 'timelock_start';
}
export interface TimelockExpiry {
  slot: UInt64;
  tag: 'timelock_expiry';
}
