// DO NOT EDIT. THIS IS A GENERATED FILE. SEE README.md.

/* eslint-disable @typescript-eslint/sort-type-constituents */
export type AnalyticsEventName =
  | '$feature_view'
  | '$feature_interaction'
  | 'wallet | session start | Pageview'
  | 'wallet | session | end'
  | 'wallet | lace | press'
  | 'onboarding | new wallet | options | view'
  | 'onboarding | new wallet | press'
  | 'onboarding | restore wallet | press'
  | 'onboarding | restore wallet | enter your recovery phrase | back | press'
  | 'onboarding | restore wallet | enter your recovery phrase | next | press'
  | 'onboarding | terms and conditions | press'
  | 'onboarding | privacy policy | press'
  | 'onboarding | cookie policy | press'
  | 'onboarding | create password | next | press'
  | 'onboarding | create password | back | press'
  | 'onboarding | create password | toggle password visibility | press'
  | 'onboarding | create wallet | toggle blockchain | press'
  | 'onboarding | create wallet | finish setup | press'
  | 'onboarding | create wallet | back | press'
  | 'onboarding | create wallet | added'
  | 'onboarding | restore wallet | added'
  | 'send | add assets | press'
  | 'send | max amount | press'
  | 'send | max amount | add'
  | 'send | qr code | press'
  | 'send | address book | press'
  | 'send | note change'
  | 'send | note clear'
  | 'send | recipient address change'
  | 'send | asset input change'
  | 'send | asset input change | set'
  | 'send | review transaction | press'
  | 'send | remove asset'
  | 'send | remove asset | success'
  | 'send | select account'
  | 'send | add assets sheet | select'
  | 'send | add assets sheet | toggle nft selection'
  | 'send | add assets sheet | close'
  | 'send | add assets sheet | confirm'
  | 'send | review transaction | back | press'
  | 'send | review transaction | next | press'
  | 'send | result | success | primary button | press'
  | 'send | result | failure | primary button | press'
  | 'address book | close | press'
  | 'address book | add | press'
  | 'address book | contact | press'
  | 'address book | search | change'
  | 'send | transaction confirmation | confirm | press'
  | 'dapp connector | authorize dapp | authorize | press'
  | 'dapp connector | authorize dapp | reject | press'
  | 'dapp connector | authorize dapp | cancel | press'
  | 'dapp connector | authorize dapp | select account | press'
  | 'dapp connector | prove transaction | confirm | press'
  | 'dapp connector | prove transaction | reject | press'
  | 'dapp connector | sign data | confirm | press'
  | 'dapp connector | sign data | reject | press'
  | 'settings | network | press'
  | 'settings | theme | press'
  | 'settings | theme | light mode | press'
  | 'settings | theme | dark mode | press'
  | 'settings | theme | system mode | press'
  | 'settings | account management | press'
  | 'settings | language | press'
  | 'settings | currency | press'
  | 'settings | authorized dapps | press'
  | 'onboarding | hardware wallet | connect | press'
  | 'account management | add wallet | press'
  | 'account management | wallet settings | press'
  | 'account management | add account | press'
  | 'account management | account details | press'
  | 'network selection | network type | press'
  | 'testnet selection | testnet | press'
  | 'network selection | cancel | press'
  | 'network selection | confirm | press'
  | 'language selection | cancel | press'
  | 'language selection | confirm | press'
  | 'language selection | language | press'
  | 'currency sheet | select currency | press'
  | 'currency sheet | cancel | press'
  | 'currency sheet | confirm | press'
  | 'receive | buy assets | press'
  | 'receive | buy assets | address | press'
  | 'receive | buy assets | url | press'
  | 'receive | buy assets | url | error'
  | 'receive | copy address | success'
  | 'receive | copy address | error'
  | 'receive | account | select | press'
  | 'receive | share | press'
  | 'receive | copy address | press'
  | 'portfolio | chart | time range | press'
  | 'portfolio | account carousel | pagination | press'
  | 'portfolio | assets | tab | press'
  | 'portfolio | buy | press'
  | 'portfolio | send | press'
  | 'portfolio | receive | press'
  | 'portfolio | view accounts | press'
  | 'home | tab bar | tab | press'
  | 'home | tab bar | menu item | press'
  | 'home | tab bar | network | press'
  | 'home | tab bar | sync status | press'
  | 'staking | stake | press'
  | 'staking | pool | press'
  | 'staking | deregister | press'
  | 'staking | delegation | confirmed'
  | 'staking | deregistration | confirmed'
  | 'staking | pool | search | changed'
  | 'staking | pool | sort | press'
  | 'app lock | biometric | attempt'
  | 'app lock | biometric | success'
  | 'app lock | biometric | failed'
  | 'app lock | biometric | fallback to pin'
  | 'app lock | pin | attempt'
  | 'app lock | pin | success'
  | 'app lock | pin | failed'
  | 'account management | wallet | deleted'
  | 'account management | wallet | renamed'
  | 'account management | account | added'
  | 'account management | account | deleted'
  | 'account management | account | renamed'
  | 'notification | notification | press'
  | 'notification | subscription | press'
  | 'address book | contact | added'
  | 'address book | contact | deleted'
  | 'swaps | select token'
  | 'swaps | fetch estimate'
  | 'swaps | adjust slippage'
  | 'swaps | adjust sources'
  | 'swaps | build tx'
  | 'swaps | review tx'
  | 'swaps | sign success'
  | 'swaps | sign failure'
  | 'swaps | disclaimer | acknowledge | press'
  | 'swaps | quick amount | half | press'
  | 'swaps | quick amount | max | press'
  | 'swaps | result | retry | press'
  | 'swaps | result | copy tx id | press'
  | 'swaps | result | view in explorer | press';
