name: Continuous Integration with Datadog

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - 'release/**'
      - 'test/**'
      - 'feature/**'
  workflow_dispatch:

permissions:
  pull-requests: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  BUILD_ARTIFACT_NAME: 'lace-dev-${{ github.sha }}'

jobs:
  datadog-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Send CI metrics to Datadog
        run: |
          if [ -n "${{ secrets.DATADOG_API_KEY }}" ]; then
            curl -X POST "https://api.datadoghq.com/api/v1/series" \
              -H "Content-Type: application/json" \
              -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
              -d '{
                "series": [{
                  "metric": "github.ci.pipeline.duration",
                  "points": [[$(date +%s), ${{ github.run_duration }}]],
                  "tags": ["service:lace-wallet", "env:ci", "workflow:${{ github.workflow }}", "job:${{ github.job }}"],
                  "type": "gauge"
                }, {
                  "metric": "github.ci.pipeline.status",
                  "points": [[$(date +%s), 1]],
                  "tags": ["service:lace-wallet", "env:ci", "workflow:${{ github.workflow }}", "job:${{ github.job }}", "status:${{ job.status }}"],
                  "type": "gauge"
                }]
              }'
          fi

  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    needs: [datadog-ci]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Collect Workflow Telemetry Build Packages
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD_TESTNET }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build common
        uses: ./.github/actions/build/package
        with:
          DIR: packages/common
          NAME: packages-common

      - name: Build cardano
        uses: ./.github/actions/build/package
        with:
          DIR: packages/cardano
          NAME: packages-cardano

      - name: Build translation
        uses: ./.github/actions/build/package
        with:
          DIR: packages/translation
          NAME: packages-translation

      - name: Build core
        uses: ./.github/actions/build/package
        with:
          DIR: packages/core
          NAME: packages-core

      - name: Build staking
        uses: ./.github/actions/build/package
        with:
          DIR: packages/staking
          NAME: packages-staking

      - name: Build nami
        uses: ./.github/actions/build/package
        with:
          DIR: packages/nami
          NAME: packages-nami

      - name: Build bitcoin
        uses: ./.github/actions/build/package
        with:
          DIR: packages/bitcoin
          NAME: packages-bitcoin

      - name: Send build metrics to Datadog
        run: |
          if [ -n "${{ secrets.DATADOG_API_KEY }}" ]; then
            curl -X POST "https://api.datadoghq.com/api/v1/series" \
              -H "Content-Type: application/json" \
              -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
              -d '{
                "series": [{
                  "metric": "lace.build.packages",
                  "points": [[$(date +%s), 7]],
                  "tags": ["service:lace-wallet", "env:ci", "workflow:prepare"],
                  "type": "gauge"
                }]
              }'
          fi

  unitTests:
    name: Unit tests
    runs-on: ubuntu-22.04
    needs: prepare

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD_TESTNET }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Download packages-common
        uses: actions/download-artifact@v4
        with:
          name: packages-common
          path: packages/common/dist

      - name: Download packages-cardano
        uses: actions/download-artifact@v4
        with:
          name: packages-cardano
          path: packages/cardano/dist

      - name: Download packages-translation
        uses: actions/download-artifact@v4
        with:
          name: packages-translation
          path: packages/translation/dist

      - name: Download packages-core
        uses: actions/download-artifact@v4
        with:
          name: packages-core
          path: packages/core/dist

      - name: Download packages-staking
        uses: actions/download-artifact@v4
        with:
          name: packages-staking
          path: packages/staking/dist

      - name: Download packages-nami
        uses: actions/download-artifact@v4
        with:
          name: packages-nami
          path: packages/nami/dist

      - name: Download packages-bitcoin
        uses: actions/download-artifact@v4
        with:
          name: packages-bitcoin
          path: packages/bitcoin/dist

      - name: Collect Workflow Telemetry Unit Tests
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - name: Execute unit tests
        uses: ./.github/actions/test/unit

      - name: Send test metrics to Datadog
        run: |
          if [ -n "${{ secrets.DATADOG_API_KEY }}" ]; then
            curl -X POST "https://api.datadoghq.com/api/v1/series" \
              -H "Content-Type: application/json" \
              -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
              -d '{
                "series": [{
                  "metric": "lace.tests.unit",
                  "points": [[$(date +%s), 1]],
                  "tags": ["service:lace-wallet", "env:ci", "workflow:unitTests", "status:${{ job.status }}"],
                  "type": "gauge"
                }]
              }'
          fi

  release-pkg:
    name: Release package
    runs-on: ubuntu-22.04
    needs: prepare

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD_TESTNET }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Download packages-common
        uses: actions/download-artifact@v4
        with:
          name: packages-common
          path: packages/common/dist

      - name: Download packages-cardano
        uses: actions/download-artifact@v4
        with:
          name: packages-cardano
          path: packages/cardano/dist

      - name: Download packages-translation
        uses: actions/download-artifact@v4
        with:
          name: packages-translation
          path: packages/translation/dist

      - name: Download packages-core
        uses: actions/download-artifact@v4
        with:
          name: packages-core
          path: packages/core/dist

      - name: Download packages-staking
        uses: actions/download-artifact@v4
        with:
          name: packages-staking
          path: packages/staking/dist

      - name: Download packages-nami
        uses: actions/download-artifact@v4
        with:
          name: packages-nami
          path: packages/nami/dist

      - name: Download packages-bitcoin
        uses: actions/download-artifact@v4
        with:
          name: packages-bitcoin
          path: packages/bitcoin/dist

      - name: Collect Workflow Telemetry Release Package
        uses: catchpoint/workflow-telemetry-action@v4
        with:
          comment_on_pr: false

      - name: Execute release package
        uses: ./.github/actions/release/package

      - name: Send release metrics to Datadog
        run: |
          if [ -n "${{ secrets.DATADOG_API_KEY }}" ]; then
            curl -X POST "https://api.datadoghq.com/api/v1/series" \
              -H "Content-Type: application/json" \
              -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
              -d '{
                "series": [{
                  "metric": "lace.release.package",
                  "points": [[$(date +%s), 1]],
                  "tags": ["service:lace-wallet", "env:ci", "workflow:release-pkg", "status:${{ job.status }}"],
                  "type": "gauge"
                }]
              }'
          fi

  datadog-final:
    needs: [prepare, unitTests, release-pkg]
    runs-on: ubuntu-latest
    steps:
      - name: Send final CI metrics to Datadog
        run: |
          if [ -n "${{ secrets.DATADOG_API_KEY }}" ]; then
            curl -X POST "https://api.datadoghq.com/api/v1/events" \
              -H "Content-Type: application/json" \
              -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
              -d '{
                "title": "Lace CI Pipeline Complete",
                "text": "All CI jobs completed for ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nStatus: ${{ needs.prepare.result }}, ${{ needs.unitTests.result }}, ${{ needs.release-pkg.result }}",
                "tags": ["service:lace-wallet", "env:ci", "workflow:ci", "repo:lace"],
                "alert_type": "${{ needs.prepare.result == 'success' && needs.unitTests.result == 'success' && needs.release-pkg.result == 'success' && 'info' || 'error' }}",
                "source_type_name": "github"
              }'
          fi 