name: Safari Extension Build

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'run-safari-build') }}
    name: Build for Safari
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download Lace dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: lace
          path: apps/browser-extension-wallet/dist
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Add executable rights to extension conversion script
        run: chmod +x ./packages/e2e-tests/tools/convertChromeExtToSafari.sh
      - name: Convert Chrome extension to Safari
        run: packages/e2e-tests/tools/convertChromeExtToSafari.sh
        shell: bash
      - name: Upload unsigned Safari build
        uses: actions/upload-artifact@v3
        with:
          name: lace-safari
          path: packages/e2e-tests/wallet-extension-safari-build/Lace/wallet-extension-safari-build/extension-build/Build/Products/Release
