name: Memory Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze-memory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Volatility
        run: |
          sudo apt-get update
          sudo apt-get install volatility

      - name: Run Volatility on memory dump
        run: |
          volatility -f memory.dump --profile=LinuxUbuntu_18_04x64 linux_strings -s "password"

      - name: Check for readable passwords
        run: |
          if grep -q "password" results.txt; then
            echo "Potential readable passwords found!"
            exit 1
          else
            echo "No passwords found."
          fi
