name: Smoke Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TAGS: '@Smoke and @Testnet and not @Pending'
  BROWSER: 'chrome'
  RUN: ${{ github.run_number }}
  DISPLAY: ':99.0'

jobs:
  smokeTests:
    name: Smoke Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Decrypt test data
        working-directory: ./packages/e2e-tests
        run: ./decrypt_secret.sh
        env:
          WALLET_1_PASSWORD: ${{ secrets.WALLET_PASSWORD_TESTNET }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Node modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --check-cache --frozen-lockfile --non-interactive --loglevel=error
      - name: Build dist version of Lace
        uses: ./.github/shared/build
        with:
          LACE_EXTENSION_KEY: ${{ secrets.MANIFEST_PUBLIC_KEY }}
      - name: Start XVFB
        run: |
          Xvfb :99 &
      - name: Start Chrome driver
        working-directory: /usr/local/share/chrome_driver
        run: |
          if [ ${BROWSER} == "chrome" ]; then
            ./chromedriver -port=4444 &
          else
            echo "Skipping start of ChromeDriver"
          fi
      - name: Execute E2E tests
        id: e2e-tests
        working-directory: ./packages/e2e-tests
        env:
          WALLET_1_PASSWORD: ${{ secrets.WALLET_PASSWORD_TESTNET }}
          TEST_DAPP_URL: ${{ secrets.TEST_DAPP_URL }}
        run: ./node_modules/.bin/wdio run wdio.conf.${BROWSER}.ts --cucumberOpts.tagExpression="@Smoke and not @Pending"
      - name: Create allure properties
        if: always()
        working-directory: ./packages/e2e-tests/reports/allure/results
        run: |
          pendingCount=`grep -r "@Pending" ../../../src/features | grep "@Smoke" | wc -l | xargs`
          pending=`grep -r -h "@Pending" ../../../src/features -A 2 | grep "@Smoke" -A 2 |  grep -v -- "^--$" | sed "s/@Pending//g" | awk '{$1=$1};1' | sed "/^@/s/ /./g;/^#/s/ /./g" | xargs | sed "s/@[^ ]*/\n&/g" | sed "s/ /./"`
          echo "
          browser=${BROWSER}
          tags=${TAGS}
          platform=Linux
          Pending.and.Smoke.Count=${pendingCount}
          @Pending.and.Smoke.Scenarios=
          ${pending}
          " > environment.properties
      - name: Publish allure report to S3
        uses: andrcuns/allure-publish-action@v2.3.0
        if: always()
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.E2E_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.E2E_AWS_ACCESS_KEY }}
        with:
          storageType: s3
          resultsGlob: './packages/e2e-tests/reports/allure/results'
          bucket: lightwallet
          prefix: 'linux/${BROWSER}/${RUN}'
          copyLatest: true
          ignoreMissingResults: true
          updatePr: description
          baseUrl: 'https://${{ secrets.E2E_REPORTS_USER }}:${{ secrets.E2E_REPORTS_PASSWORD }}@${{ secrets.E2E_REPORTS_URL }}'
      - name: Publish artifacts (logs, reports, screenshots)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-artifacts
          path: |
            ./packages/e2e-tests/screenshots
            ./packages/e2e-tests/logs
            ./packages/e2e-tests/reports
          retention-days: 5
