name: Smoke Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  actions: read

env:
  TAGS: '@Smoke and @Testnet'
  BROWSER: 'chrome'
  RUN: ${{ github.run_number }}
  DISPLAY: ':99.0'
  BRANCH: ${{ github.ref_name }}

jobs:
  smokeTests:
    name: Smoke Tests
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Collect Workflow Telemetry Build Packages
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - name: Decrypt test data
        working-directory: ./packages/e2e-tests
        run: ./decrypt_secret.sh
        env:
          WALLET_1_PASSWORD: ${{ secrets.WALLET_PASSWORD_TESTNET }}
      - name: Build dist version of Lace
        uses: ./.github/shared/build
        with:
          LACE_EXTENSION_KEY: ${{ secrets.MANIFEST_PUBLIC_KEY }}
      - name: Start XVFB
        run: |
          Xvfb :99 &
      - name: Execute E2E tests
        id: e2e-tests
        working-directory: ./packages/e2e-tests
        env:
          WALLET_1_PASSWORD: ${{ secrets.WALLET_PASSWORD_TESTNET }}
          TEST_DAPP_URL: ${{ secrets.TEST_DAPP_URL }}
        run: yarn wdio run wdio.conf.${BROWSER}.ts --cucumberOpts.tags="@Smoke and not @Pending"
      - name: Create allure properties
        if: always()
        working-directory: ./packages/e2e-tests/reports/allure/results
        run: |
          echo "
          branch=${BRANCH}
          browser=${BROWSER}
          tags=${TAGS}
          platform=Linux
          " > environment.properties
      - name: Publish allure report to S3
        uses: andrcuns/allure-publish-action@v2.6.0
        if: always()
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.E2E_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.E2E_AWS_SECRET_ACCESS_KEY }}
        with:
          storageType: s3
          resultsGlob: './packages/e2e-tests/reports/allure/results'
          bucket: lace-e2e-test-results
          prefix: 'smoke/linux/${BROWSER}/${RUN}'
          copyLatest: true
          ignoreMissingResults: true
          updatePr: comment
          baseUrl: 'https://${{ secrets.E2E_REPORTS_USER }}:${{ secrets.E2E_REPORTS_PASSWORD }}@${{ secrets.E2E_REPORTS_URL }}'
      - name: Publish artifacts (logs, reports, screenshots)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: |
            ./packages/e2e-tests/screenshots
            ./packages/e2e-tests/logs
            ./packages/e2e-tests/reports
          retention-days: 5
