on:
  push:
    branches:
      - main
name: SonarQube scanner
jobs:
  sonarQubeTrigger:
    name: SonarQube
    runs-on: ubuntu-latest
    env:
      SONARCLOUD_URL: https://sonar.atixlabs.com/
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Node modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive --loglevel=error
      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=8192 --openssl-legacy-provider'
        run: yarn build
      - name: test
        run: yarn test:coverage
      - name: Sonar - @lace/cardano
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/cardano
          args: >
            -Dsonar.projectKey=iohk-lightwallet:cardano
            -Dsonar.language=ts
            -Dsonar.sources=src
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.mock.ts,node_modules/*
      - name: Sonar - @lace/core
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/core
          args: >
            -Dsonar.projectKey=iohk-lightwallet:core
            -Dsonar.language=ts
            -Dsonar.sources=src
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.mock.ts,node_modules/*
      - name: Sonar - @lace/common
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/common
          args: >
            -Dsonar.projectKey=iohk-lightwallet:common
            -Dsonar.language=ts
            -Dsonar.sources=src
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.mock.ts,node_modules/*
      - name: Sonar - @light-wallet/apps/browser-extension-wallet
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: apps/browser-extension-wallet
          args: >
            -Dsonar.projectKey=iohk-lightwallet:browser-extension
            -Dsonar.language=ts
            -Dsonar.sources=src
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.mock.ts,node_modules/*
