name: Test Datadog v2 API

on:
  workflow_dispatch:
  push:
    branches: [ main, test/berno_prom_metrics ]

jobs:
  test-datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Datadog v2 API
        run: |
          echo "🔍 Starting Datadog v2 API test..."
          echo "📊 API Key present: $([ -n "${{ secrets.DATADOG_API_KEY }}" ] && echo "YES" || echo "NO")"
          echo "🌐 Datadog Site: us5.datadoghq.com"
          echo "⏰ Timestamp: $(date)"
          echo "📝 Workflow: ${{ github.workflow }}"
          echo "🏷️ Repository: ${{ github.repository }}"
          echo "🌿 Branch: ${{ github.ref_name }}"
          echo "🔗 Commit: ${{ github.sha }}"
          echo ""
          
          if [ -n "${{ secrets.DATADOG_API_KEY }}" ]; then
            echo "✅ API Key is set, proceeding with test..."
            
            # Prepare the JSON payload (v2 API format) - Testing CI metrics
            json_payload="{
              \"series\": [{
                \"metric\": \"test.datadog.integration\",
                \"points\": [{\"timestamp\": $(date +%s), \"value\": 42}],
                \"tags\": [\"service:lace-wallet\", \"env:test\", \"workflow:test-datadog\"]
              }, {
                \"metric\": \"test.datadog.simple\",
                \"points\": [{\"timestamp\": $(date +%s), \"value\": 100}],
                \"tags\": [\"service:lace-wallet\", \"env:test\", \"workflow:test-datadog\"]
              }, {
                \"metric\": \"github.ci.pipeline.duration\",
                \"points\": [{\"timestamp\": $(date +%s), \"value\": 120}],
                \"tags\": [\"service:lace-wallet\", \"env:test\", \"workflow:test-datadog\", \"job:test-datadog\"]
              }, {
                \"metric\": \"github.ci.pipeline.status\",
                \"points\": [{\"timestamp\": $(date +%s), \"value\": 1}],
                \"tags\": [\"service:lace-wallet\", \"env:test\", \"workflow:test-datadog\", \"status:success\"]
              }]
            }"
            
            echo "📤 Sending JSON payload:"
            echo "$json_payload"
            echo ""
            echo "🔍 JSON validation:"
            echo "$json_payload" | jq '.' 2>/dev/null && echo "✅ JSON is valid" || echo "❌ JSON is invalid"
            echo ""
            
            # Send metrics to Datadog v2 API
            echo "🚀 Sending request to Datadog v2 API..."
            response=$(curl -s -w "\nHTTP_STATUS_CODE:%{http_code}\nTOTAL_TIME:%{time_total}s\n" \
              -X POST "https://api.us5.datadoghq.com/api/v2/series" \
              -H "Content-Type: application/json" \
              -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
              -d "$json_payload")
            
            echo "📥 Raw response:"
            echo "$response"
            echo ""
            
            # Extract HTTP status code
            http_code=$(echo "$response" | grep "HTTP_STATUS_CODE:" | cut -d: -f2)
            total_time=$(echo "$response" | grep "TOTAL_TIME:" | cut -d: -f2)
            response_body=$(echo "$response" | sed '/HTTP_STATUS_CODE:/d' | sed '/TOTAL_TIME:/d')
            
            echo "📊 Response Analysis:"
            echo "   HTTP Status Code: $http_code"
            echo "   Response Time: ${total_time}s"
            echo "   Response Body: $response_body"
            echo ""
            
            if [ "$http_code" = "202" ]; then
              echo "✅ SUCCESS: Metrics sent successfully to Datadog!"
              echo "   Status: $http_code"
              echo "   Time: ${total_time}s"
            else
              echo "❌ ERROR: Failed to send metrics to Datadog"
              echo "   Status: $http_code"
              echo "   Error: $response_body"
              echo ""
              echo "🔍 Troubleshooting tips:"
              echo "   1. Check API key permissions in Datadog"
              echo "   2. Verify the API key is correct"
              echo "   3. Check if the key has 'Metrics Write' permission"
              echo "   4. Ensure you're looking at us5.datadoghq.com"
            fi
            
            # Test CI Events functionality
            echo ""
            echo "📝 Testing CI Events..."
            event_payload="{
              \"title\": \"Test Datadog CI Event: ${{ github.workflow }}\",
              \"text\": \"Test workflow ${{ github.workflow }} completed successfully\\nRepository: ${{ github.repository }}\\nBranch: ${{ github.ref_name }}\\nCommit: ${{ github.sha }}\",
              \"tags\": [\"service:lace-wallet\", \"env:test\", \"workflow:test-datadog\", \"status:success\", \"repo:${{ github.repository }}\"],
              \"alert_type\": \"info\",
              \"source_type_name\": \"github\"
            }"
            
            echo "📤 Sending CI event payload:"
            echo "$event_payload"
            echo ""
            echo "🔍 JSON validation for event:"
            echo "$event_payload" | jq '.' 2>/dev/null && echo "✅ Event JSON is valid" || echo "❌ Event JSON is invalid"
            echo ""
            
            event_response=$(curl -s -w "\nHTTP_STATUS_CODE:%{http_code}\nTOTAL_TIME:%{time_total}s\n" \
              -X POST "https://api.us5.datadoghq.com/api/v1/events" \
              -H "Content-Type: application/json" \
              -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
              -d "$event_payload")
            
            echo "📥 Raw event response:"
            echo "$event_response"
            echo ""
            
            event_http_code=$(echo "$event_response" | grep "HTTP_STATUS_CODE:" | cut -d: -f2)
            event_total_time=$(echo "$event_response" | grep "TOTAL_TIME:" | cut -d: -f2)
            event_response_body=$(echo "$event_response" | sed '/HTTP_STATUS_CODE:/d' | sed '/TOTAL_TIME:/d')
            
            echo "📊 Event Response Analysis:"
            echo "   HTTP Status Code: $event_http_code"
            echo "   Response Time: ${event_total_time}s"
            echo "   Response Body: $event_response_body"
            echo ""
            
            if [ "$event_http_code" = "202" ]; then
              echo "✅ SUCCESS: CI Event sent successfully to Datadog!"
              echo "   Status: $event_http_code"
              echo "   Time: ${event_total_time}s"
            else
              echo "❌ ERROR: Failed to send CI Event to Datadog"
              echo "   Status: $event_http_code"
              echo "   Error: $event_response_body"
              echo ""
              echo "🔍 Event troubleshooting tips:"
              echo "   1. Check if API key has 'Events Write' permission"
              echo "   2. Verify the event payload format"
              echo "   3. Check Datadog v1 events API documentation"
              echo "   4. Ensure you're using the correct endpoint"
            fi
            
            # Try alternative event format if first one failed
            if [ "$event_http_code" != "202" ]; then
              echo ""
              echo "🔄 Trying alternative event format..."
              simple_event_payload="{
                \"title\": \"Test CI Event\",
                \"text\": \"Simple test event from GitHub Actions\",
                \"tags\": [\"service:lace-wallet\", \"env:test\"],
                \"alert_type\": \"info\"
              }"
              
              echo "📤 Sending simple event payload:"
              echo "$simple_event_payload"
              echo ""
              
              simple_event_response=$(curl -s -w "\nHTTP_STATUS_CODE:%{http_code}\nTOTAL_TIME:%{time_total}s\n" \
                -X POST "https://api.us5.datadoghq.com/api/v1/events" \
                -H "Content-Type: application/json" \
                -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
                -d "$simple_event_payload")
              
              simple_event_http_code=$(echo "$simple_event_response" | grep "HTTP_STATUS_CODE:" | cut -d: -f2)
              simple_event_response_body=$(echo "$simple_event_response" | sed '/HTTP_STATUS_CODE:/d' | sed '/TOTAL_TIME:/d')
              
              if [ "$simple_event_http_code" = "202" ]; then
                echo "✅ SUCCESS: Simple CI Event sent successfully to Datadog!"
              else
                echo "❌ ERROR: Simple CI Event also failed"
                echo "   Status: $simple_event_http_code"
                echo "   Error: $simple_event_response_body"
              fi
            fi
            
            echo ""
            echo "🔍 To verify in Datadog UI:"
            echo "   1. Go to Metrics Explorer"
            echo "   2. Search for: test.datadog.integration"
            echo "   3. Set time range to 'Last 1 hour'"
            echo "   4. Look for metrics with tags: service:lace-wallet, env:test"
            echo ""
            echo "📊 Also check for CI metrics:"
            echo "   5. Search for: github.ci.pipeline.duration"
            echo "   6. Search for: github.ci.pipeline.status"
            echo "   7. Check Events tab for CI events"
            echo "   8. Look for event titled: 'Test Datadog CI Event: test-datadog'"
            
          else
            echo "❌ ERROR: DATADOG_API_KEY secret is not set"
            echo ""
            echo "🔧 To fix this:"
            echo "   1. Go to repository Settings → Secrets and variables → Actions"
            echo "   2. Add a new repository secret named 'DATADOG_API_KEY'"
            echo "   3. Set the value to your Datadog API key"
            echo "   4. Make sure the key has 'Metrics Write' permission"
          fi
          
          echo ""
          echo "🏁 Test completed at $(date)" 